// This file was automatically generated by make-pins.py
//
// --af boards/stm32l4r9i_af.csv
// --board boards/STM32L4R9IDISC/pins.csv
// --prefix boards/stm32f4xx_prefix.c

// stm32f4xx_prefix.c becomes the initial portion of the generated pins file.

#include <stdio.h>

#include "py/obj.h"
#include "py/mphal.h"
#include "pin.h"

#define AF(af_idx, af_fn, af_unit, af_type, af_ptr) \
{ \
    { &pin_af_type }, \
    .name = MP_QSTR_AF ## af_idx ## _ ## af_fn ## af_unit, \
    .idx = (af_idx), \
    .fn = AF_FN_ ## af_fn, \
    .unit = (af_unit), \
    .type = AF_PIN_TYPE_ ## af_fn ## _ ## af_type, \
    .reg = (af_ptr) \
}

#define PIN(p_port, p_pin, p_af, p_adc_num, p_adc_channel) \
{ \
    { &pin_type }, \
    .name = MP_QSTR_ ## p_port ## p_pin, \
    .port = PORT_ ## p_port, \
    .pin = (p_pin), \
    .num_af = (sizeof(p_af) / sizeof(pin_af_obj_t)), \
    .pin_mask = (1 << ((p_pin) & 0x0f)), \
    .gpio = GPIO ## p_port, \
    .af = p_af, \
    .adc_num = p_adc_num, \
    .adc_channel = p_adc_channel, \
}

const pin_af_obj_t pin_A0_af[] = {
  AF( 1, TIM     ,  2, CH1       , TIM2    ), // TIM2_CH1
  AF( 2, TIM     ,  5, CH1       , TIM5    ), // TIM5_CH1
  AF( 3, TIM     ,  8, ETR       , TIM8    ), // TIM8_ETR
  //( 7, USART   ,  2, CTS_NSS   , USART2  ), // USART2_CTS_NSS
#if defined(MICROPY_HW_UART4_TX)
  AF( 8, UART    ,  4, TX        , UART4   ), // UART4_TX
#endif
  //(13, SAI     ,  1, EXTCLK    , SAI1    ), // SAI1_EXTCLK
  AF(14, TIM     ,  2, ETR       , TIM2    ), // TIM2_ETR
  //(15, EVENTOUT ,  0,           , EVENTOUT ), // EVENTOUT 
};

const pin_obj_t pin_A0_obj = PIN(A, 0, pin_A0_af, PIN_ADC1, 5);

const pin_af_obj_t pin_A1_af[] = {
  AF( 1, TIM     ,  2, CH2       , TIM2    ), // TIM2_CH2
  AF( 2, TIM     ,  5, CH2       , TIM5    ), // TIM5_CH2
  //( 4, I2C     ,  1, SMBA      , I2C1    ), // I2C1_SMBA
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, SCK       , SPI1    ), // SPI1_SCK
#endif
  //( 7, USART   ,  2, RTS_DE    , USART2  ), // USART2_RTS_DE
#if defined(MICROPY_HW_UART4_TX)
  AF( 8, UART    ,  4, RX        , UART4   ), // UART4_RX
#endif
  //(10, OCTOSPIM,  0, P1_DQS    , OCTOSPIM), // OCTOSPIM_P1_DQS
  AF(14, TIM     , 15, CH1N      , TIM15   ), // TIM15_CH1N
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A1_obj = PIN(A, 1, pin_A1_af, PIN_ADC1, 6);

const pin_af_obj_t pin_A2_af[] = {
  AF( 1, TIM     ,  2, CH3       , TIM2    ), // TIM2_CH3
  AF( 2, TIM     ,  5, CH3       , TIM5    ), // TIM5_CH3
#if defined(MICROPY_HW_UART2_TX)
  AF( 7, USART   ,  2, TX        , USART2  ), // USART2_TX
#endif
  //( 8, LPUART  ,  1, TX        , LPUART1 ), // LPUART1_TX
  //(10, OCTOSPIM,  0, P1_NCS    , OCTOSPIM), // OCTOSPIM_P1_NCS
  //(13, SAI     ,  2, EXTCLK    , SAI2    ), // SAI2_EXTCLK
  AF(14, TIM     , 15, CH1       , TIM15   ), // TIM15_CH1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A2_obj = PIN(A, 2, pin_A2_af, PIN_ADC1, 7);

const pin_af_obj_t pin_A3_af[] = {
  AF( 1, TIM     ,  2, CH4       , TIM2    ), // TIM2_CH4
  AF( 2, TIM     ,  5, CH4       , TIM5    ), // TIM5_CH4
  //( 3, SAI     ,  1, CK1       , SAI1    ), // SAI1_CK1
#if defined(MICROPY_HW_UART2_TX)
  AF( 7, USART   ,  2, RX        , USART2  ), // USART2_RX
#endif
  //( 8, LPUART  ,  1, RX        , LPUART1 ), // LPUART1_RX
  //(10, OCTOSPIM,  0, P1_CLK    , OCTOSPIM), // OCTOSPIM_P1_CLK
  //(13, SAI     ,  1, MCLK_A    , SAI1    ), // SAI1_MCLK_A
  AF(14, TIM     , 15, CH2       , TIM15   ), // TIM15_CH2
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A3_obj = PIN(A, 3, pin_A3_af, PIN_ADC1, 8);

const pin_af_obj_t pin_A4_af[] = {
  //( 3, OCTOSPIM,  0, P1_NCS    , OCTOSPIM), // OCTOSPIM_P1_NCS
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, NSS       , SPI1    ), // SPI1_NSS
#endif
#if defined(MICROPY_HW_SPI3_SCK)
  AF( 6, SPI     ,  3, NSS       , SPI3    ), // SPI3_NSS
#endif
#if defined(MICROPY_HW_UART2_TX)
  AF( 7, USART   ,  2, CK        , USART2  ), // USART2_CK
#endif
  //(10, DCMI    ,  0, HSYNC     , DCMI    ), // DCMI_HSYNC
  //(13, SAI     ,  1, FS_B      , SAI1    ), // SAI1_FS_B
  //(14, LPTIM   ,  2, OUT       , LPTIM2  ), // LPTIM2_OUT
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A4_obj = PIN(A, 4, pin_A4_af, PIN_ADC1, 9);

const pin_af_obj_t pin_A5_af[] = {
  AF( 1, TIM     ,  2, CH1       , TIM2    ), // TIM2_CH1
  AF( 2, TIM     ,  2, ETR       , TIM2    ), // TIM2_ETR
  AF( 3, TIM     ,  8, CH1N      , TIM8    ), // TIM8_CH1N
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, SCK       , SPI1    ), // SPI1_SCK
#endif
  //(14, LPTIM   ,  2, ETR       , LPTIM2  ), // LPTIM2_ETR
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A5_obj = PIN(A, 5, pin_A5_af, PIN_ADC1, 10);

const pin_af_obj_t pin_A6_af[] = {
  AF( 1, TIM     ,  1, BKIN      , TIM1    ), // TIM1_BKIN
  AF( 2, TIM     ,  3, CH1       , TIM3    ), // TIM3_CH1
  AF( 3, TIM     ,  8, BKIN      , TIM8    ), // TIM8_BKIN
  //( 4, DCMI    ,  0, PIXCLK    , DCMI    ), // DCMI_PIXCLK
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, MISO      , SPI1    ), // SPI1_MISO
#endif
  //( 7, USART   ,  3, CTS_NSS   , USART3  ), // USART3_CTS_NSS
  //( 8, LPUART  ,  1, CTS       , LPUART1 ), // LPUART1_CTS
  //(10, OCTOSPIM,  0, P1_IO3    , OCTOSPIM), // OCTOSPIM_P1_IO3
  AF(12, TIM     ,  1, BKIN      , TIM1    ), // TIM1_BKIN
  AF(13, TIM     ,  8, BKIN      , TIM8    ), // TIM8_BKIN
  AF(14, TIM     , 16, CH1       , TIM16   ), // TIM16_CH1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A6_obj = PIN(A, 6, pin_A6_af, PIN_ADC1, 11);

const pin_af_obj_t pin_A7_af[] = {
  AF( 1, TIM     ,  1, CH1N      , TIM1    ), // TIM1_CH1N
  AF( 2, TIM     ,  3, CH2       , TIM3    ), // TIM3_CH2
  AF( 3, TIM     ,  8, CH1N      , TIM8    ), // TIM8_CH1N
#if defined(MICROPY_HW_I2C3_SCL)
  AF( 4, I2C     ,  3, SCL       , I2C3    ), // I2C3_SCL
#endif
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, MOSI      , SPI1    ), // SPI1_MOSI
#endif
  //(10, OCTOSPIM,  0, P1_IO2    , OCTOSPIM), // OCTOSPIM_P1_IO2
  AF(14, TIM     , 17, CH1       , TIM17   ), // TIM17_CH1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A7_obj = PIN(A, 7, pin_A7_af, PIN_ADC1, 12);

const pin_af_obj_t pin_A8_af[] = {
  //( 0, MCO     ,  0,           , MCO     ), // MCO
  AF( 1, TIM     ,  1, CH1       , TIM1    ), // TIM1_CH1
  //( 3, SAI     ,  1, CK2       , SAI1    ), // SAI1_CK2
#if defined(MICROPY_HW_UART1_TX)
  AF( 7, USART   ,  1, CK        , USART1  ), // USART1_CK
#endif
  //(10, OTG     ,  0, FS_SOF    , OTG     ), // OTG_FS_SOF
  //(13, SAI     ,  1, SCK_A     , SAI1    ), // SAI1_SCK_A
  //(14, LPTIM   ,  2, OUT       , LPTIM2  ), // LPTIM2_OUT
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A8_obj = PIN(A, 8, pin_A8_af, 0, 0);

const pin_af_obj_t pin_A9_af[] = {
  AF( 1, TIM     ,  1, CH2       , TIM1    ), // TIM1_CH2
#if defined(MICROPY_HW_SPI2_SCK)
  AF( 3, SPI     ,  2, SCK       , SPI2    ), // SPI2_SCK
#endif
  //( 5, DCMI    ,  0, D0        , DCMI    ), // DCMI_D0
#if defined(MICROPY_HW_UART1_TX)
  AF( 7, USART   ,  1, TX        , USART1  ), // USART1_TX
#endif
  //(13, SAI     ,  1, FS_A      , SAI1    ), // SAI1_FS_A
  AF(14, TIM     , 15, BKIN      , TIM15   ), // TIM15_BKIN
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A9_obj = PIN(A, 9, pin_A9_af, 0, 0);

const pin_af_obj_t pin_A10_af[] = {
  AF( 1, TIM     ,  1, CH3       , TIM1    ), // TIM1_CH3
  //( 3, SAI     ,  1, D1        , SAI1    ), // SAI1_D1
  //( 5, DCMI    ,  0, D1        , DCMI    ), // DCMI_D1
#if defined(MICROPY_HW_UART1_TX)
  AF( 7, USART   ,  1, RX        , USART1  ), // USART1_RX
#endif
  //(10, OTG     ,  0, FS_ID     , OTG     ), // OTG_FS_ID
  //(13, SAI     ,  1, SD_A      , SAI1    ), // SAI1_SD_A
  AF(14, TIM     , 17, BKIN      , TIM17   ), // TIM17_BKIN
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A10_obj = PIN(A, 10, pin_A10_af, 0, 0);

const pin_af_obj_t pin_A11_af[] = {
  AF( 1, TIM     ,  1, CH4       , TIM1    ), // TIM1_CH4
  //( 2, TIM     ,  1, BKIN2     , TIM1    ), // TIM1_BKIN2
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, MISO      , SPI1    ), // SPI1_MISO
#endif
  //( 7, USART   ,  1, CTS_NSS   , USART1  ), // USART1_CTS_NSS
#if defined(MICROPY_HW_CAN1_TX)
  AF( 9, CAN     ,  1, RX        , CAN1    ), // CAN1_RX
#endif
  //(10, OTG     ,  0, FS_DM     , OTG     ), // OTG_FS_DM
  //(12, TIM     ,  1, BKIN2     , TIM1    ), // TIM1_BKIN2
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A11_obj = PIN(A, 11, pin_A11_af, 0, 0);

const pin_af_obj_t pin_A12_af[] = {
  AF( 1, TIM     ,  1, ETR       , TIM1    ), // TIM1_ETR
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, MOSI      , SPI1    ), // SPI1_MOSI
#endif
  //( 7, USART   ,  1, RTS_DE    , USART1  ), // USART1_RTS_DE
#if defined(MICROPY_HW_CAN1_TX)
  AF( 9, CAN     ,  1, TX        , CAN1    ), // CAN1_TX
#endif
  //(10, OTG     ,  0, FS_DP     , OTG     ), // OTG_FS_DP
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A12_obj = PIN(A, 12, pin_A12_af, 0, 0);

// const pin_af_obj_t pin_A13_af[] = {
  //( 0, JTMS    ,  0,           , JTMS    ), // JTMS
  //( 0, SWDIO   ,  0,           , SWDIO   ), // SWDIO
  //( 1, IR      ,  0, OUT       , IR      ), // IR_OUT
  //(10, OTG     ,  0, FS_NOE    , OTG     ), // OTG_FS_NOE
  //(13, SAI     ,  1, SD_B      , SAI1    ), // SAI1_SD_B
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_A13_obj = PIN(A, 13, NULL, 0, 0);

// const pin_af_obj_t pin_A14_af[] = {
  //( 0, JTCK    ,  0,           , JTCK    ), // JTCK
  //( 0, SWCLK   ,  0,           , SWCLK   ), // SWCLK
  //( 1, LPTIM   ,  1, OUT       , LPTIM1  ), // LPTIM1_OUT
  //( 4, I2C     ,  1, SMBA      , I2C1    ), // I2C1_SMBA
  //( 5, I2C     ,  4, SMBA      , I2C4    ), // I2C4_SMBA
  //(10, OTG     ,  0, FS_SOF    , OTG     ), // OTG_FS_SOF
  //(13, SAI     ,  1, FS_B      , SAI1    ), // SAI1_FS_B
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_A14_obj = PIN(A, 14, NULL, 0, 0);

const pin_af_obj_t pin_A15_af[] = {
  //( 0, JTDI    ,  0,           , JTDI    ), // JTDI
  AF( 1, TIM     ,  2, CH1       , TIM2    ), // TIM2_CH1
  AF( 2, TIM     ,  2, ETR       , TIM2    ), // TIM2_ETR
#if defined(MICROPY_HW_UART2_TX)
  AF( 3, USART   ,  2, RX        , USART2  ), // USART2_RX
#endif
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, NSS       , SPI1    ), // SPI1_NSS
#endif
#if defined(MICROPY_HW_SPI3_SCK)
  AF( 6, SPI     ,  3, NSS       , SPI3    ), // SPI3_NSS
#endif
  //( 7, USART   ,  3, RTS_DE    , USART3  ), // USART3_RTS_DE
  //( 8, UART    ,  4, RTS_DE    , UART4   ), // UART4_RTS_DE
  //( 9, TSC     ,  0, G3_IO1    , TSC     ), // TSC_G3_IO1
  //(13, SAI     ,  2, FS_B      , SAI2    ), // SAI2_FS_B
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_A15_obj = PIN(A, 15, pin_A15_af, 0, 0);

const pin_af_obj_t pin_B0_af[] = {
  AF( 1, TIM     ,  1, CH2N      , TIM1    ), // TIM1_CH2N
  AF( 2, TIM     ,  3, CH3       , TIM3    ), // TIM3_CH3
  AF( 3, TIM     ,  8, CH2N      , TIM8    ), // TIM8_CH2N
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, NSS       , SPI1    ), // SPI1_NSS
#endif
#if defined(MICROPY_HW_UART3_TX)
  AF( 7, USART   ,  3, CK        , USART3  ), // USART3_CK
#endif
  //(10, OCTOSPIM,  0, P1_IO1    , OCTOSPIM), // OCTOSPIM_P1_IO1
  //(12, COMP    ,  1, OUT       , COMP1   ), // COMP1_OUT
  //(13, SAI     ,  1, EXTCLK    , SAI1    ), // SAI1_EXTCLK
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B0_obj = PIN(B, 0, pin_B0_af, PIN_ADC1, 15);

const pin_af_obj_t pin_B1_af[] = {
  AF( 1, TIM     ,  1, CH3N      , TIM1    ), // TIM1_CH3N
  AF( 2, TIM     ,  3, CH4       , TIM3    ), // TIM3_CH4
  AF( 3, TIM     ,  8, CH3N      , TIM8    ), // TIM8_CH3N
  //( 6, DFSDM   ,  1, DATIN0    , DFSDM1  ), // DFSDM1_DATIN0
  //( 7, USART   ,  3, RTS_DE    , USART3  ), // USART3_RTS_DE
  //( 8, LPUART  ,  1, RTS_DE    , LPUART1 ), // LPUART1_RTS_DE
  //(10, OCTOSPIM,  0, P1_IO0    , OCTOSPIM), // OCTOSPIM_P1_IO0
  //(14, LPTIM   ,  2, IN1       , LPTIM2  ), // LPTIM2_IN1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B1_obj = PIN(B, 1, pin_B1_af, PIN_ADC1, 16);

// const pin_af_obj_t pin_B2_af[] = {
  //( 0, RTC     ,  0, OUT       , RTC     ), // RTC_OUT
  //( 1, LPTIM   ,  1, OUT       , LPTIM1  ), // LPTIM1_OUT
  //( 4, I2C     ,  3, SMBA      , I2C3    ), // I2C3_SMBA
  //( 6, DFSDM   ,  1, CKIN0     , DFSDM1  ), // DFSDM1_CKIN0
  //(10, OCTOSPIM,  0, P1_DQS    , OCTOSPIM), // OCTOSPIM_P1_DQS
  //(11, LCD     ,  0, B1        , LCD     ), // LCD_B1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_B2_obj = PIN(B, 2, NULL, 0, 0);

const pin_af_obj_t pin_B3_af[] = {
  //( 0, JTDO    ,  0,           , JTDO    ), // JTDO
  //( 0, TRACESWO,  0,           , TRACESWO), // TRACESWO
  AF( 1, TIM     ,  2, CH2       , TIM2    ), // TIM2_CH2
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, SCK       , SPI1    ), // SPI1_SCK
#endif
#if defined(MICROPY_HW_SPI3_SCK)
  AF( 6, SPI     ,  3, SCK       , SPI3    ), // SPI3_SCK
#endif
  //( 7, USART   ,  1, RTS_DE    , USART1  ), // USART1_RTS_DE
  //(10, OTG     ,  0, FS_CRS_SYNC, OTG     ), // OTG_FS_CRS_SYNC
  //(13, SAI     ,  1, SCK_B     , SAI1    ), // SAI1_SCK_B
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B3_obj = PIN(B, 3, pin_B3_af, 0, 0);

const pin_af_obj_t pin_B4_af[] = {
  //( 0, NJTRST  ,  0,           , NJTRST  ), // NJTRST
  AF( 2, TIM     ,  3, CH1       , TIM3    ), // TIM3_CH1
#if defined(MICROPY_HW_I2C3_SCL)
  AF( 4, I2C     ,  3, SDA       , I2C3    ), // I2C3_SDA
#endif
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, MISO      , SPI1    ), // SPI1_MISO
#endif
#if defined(MICROPY_HW_SPI3_SCK)
  AF( 6, SPI     ,  3, MISO      , SPI3    ), // SPI3_MISO
#endif
  //( 7, USART   ,  1, CTS_NSS   , USART1  ), // USART1_CTS_NSS
  //( 8, UART    ,  5, RTS_DE    , UART5   ), // UART5_RTS_DE
  //( 9, TSC     ,  0, G2_IO1    , TSC     ), // TSC_G2_IO1
  //(10, DCMI    ,  0, D12       , DCMI    ), // DCMI_D12
  //(13, SAI     ,  1, MCLK_B    , SAI1    ), // SAI1_MCLK_B
  AF(14, TIM     , 17, BKIN      , TIM17   ), // TIM17_BKIN
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B4_obj = PIN(B, 4, pin_B4_af, 0, 0);

const pin_af_obj_t pin_B5_af[] = {
  //( 1, LPTIM   ,  1, IN1       , LPTIM1  ), // LPTIM1_IN1
  AF( 2, TIM     ,  3, CH2       , TIM3    ), // TIM3_CH2
  //( 4, I2C     ,  1, SMBA      , I2C1    ), // I2C1_SMBA
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, MOSI      , SPI1    ), // SPI1_MOSI
#endif
#if defined(MICROPY_HW_SPI3_SCK)
  AF( 6, SPI     ,  3, MOSI      , SPI3    ), // SPI3_MOSI
#endif
#if defined(MICROPY_HW_UART1_TX)
  AF( 7, USART   ,  1, CK        , USART1  ), // USART1_CK
#endif
#if defined(MICROPY_HW_UART5_TX)
  AF( 8, UART    ,  5, CTS       , UART5   ), // UART5_CTS
#endif
  //( 9, TSC     ,  0, G2_IO2    , TSC     ), // TSC_G2_IO2
  //(10, DCMI    ,  0, D10       , DCMI    ), // DCMI_D10
  //(12, COMP    ,  2, OUT       , COMP2   ), // COMP2_OUT
  //(13, SAI     ,  1, SD_B      , SAI1    ), // SAI1_SD_B
  AF(14, TIM     , 16, BKIN      , TIM16   ), // TIM16_BKIN
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B5_obj = PIN(B, 5, pin_B5_af, 0, 0);

const pin_af_obj_t pin_B6_af[] = {
  //( 1, LPTIM   ,  1, ETR       , LPTIM1  ), // LPTIM1_ETR
  AF( 2, TIM     ,  4, CH1       , TIM4    ), // TIM4_CH1
  //( 3, TIM     ,  8, BKIN2     , TIM8    ), // TIM8_BKIN2
#if defined(MICROPY_HW_I2C1_SCL)
  AF( 4, I2C     ,  1, SCL       , I2C1    ), // I2C1_SCL
#endif
#if defined(MICROPY_HW_I2C4_SCL)
  AF( 5, I2C     ,  4, SCL       , I2C4    ), // I2C4_SCL
#endif
  //( 6, DFSDM   ,  1, DATIN5    , DFSDM1  ), // DFSDM1_DATIN5
#if defined(MICROPY_HW_UART1_TX)
  AF( 7, USART   ,  1, TX        , USART1  ), // USART1_TX
#endif
  //( 9, TSC     ,  0, G2_IO3    , TSC     ), // TSC_G2_IO3
  //(10, DCMI    ,  0, D5        , DCMI    ), // DCMI_D5
  //(12, TIM     ,  8, BKIN2     , TIM8    ), // TIM8_BKIN2
  //(13, SAI     ,  1, FS_B      , SAI1    ), // SAI1_FS_B
  AF(14, TIM     , 16, CH1N      , TIM16   ), // TIM16_CH1N
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B6_obj = PIN(B, 6, pin_B6_af, 0, 0);

const pin_af_obj_t pin_B7_af[] = {
  //( 1, LPTIM   ,  1, IN2       , LPTIM1  ), // LPTIM1_IN2
  AF( 2, TIM     ,  4, CH2       , TIM4    ), // TIM4_CH2
  AF( 3, TIM     ,  8, BKIN      , TIM8    ), // TIM8_BKIN
#if defined(MICROPY_HW_I2C1_SCL)
  AF( 4, I2C     ,  1, SDA       , I2C1    ), // I2C1_SDA
#endif
#if defined(MICROPY_HW_I2C4_SCL)
  AF( 5, I2C     ,  4, SDA       , I2C4    ), // I2C4_SDA
#endif
  //( 6, DFSDM   ,  1, CKIN5     , DFSDM1  ), // DFSDM1_CKIN5
#if defined(MICROPY_HW_UART1_TX)
  AF( 7, USART   ,  1, RX        , USART1  ), // USART1_RX
#endif
#if defined(MICROPY_HW_UART4_TX)
  AF( 8, UART    ,  4, CTS       , UART4   ), // UART4_CTS
#endif
  //( 9, TSC     ,  0, G2_IO4    , TSC     ), // TSC_G2_IO4
  //(10, DCMI    ,  0, VSYNC     , DCMI    ), // DCMI_VSYNC
  //(11, DSI     ,  0, TE        , DSI     ), // DSI_TE
  //(12, FMC     ,  0, NL        , FMC     ), // FMC_NL
  AF(13, TIM     ,  8, BKIN      , TIM8    ), // TIM8_BKIN
  AF(14, TIM     , 17, CH1N      , TIM17   ), // TIM17_CH1N
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B7_obj = PIN(B, 7, pin_B7_af, 0, 0);

const pin_af_obj_t pin_B8_af[] = {
  AF( 2, TIM     ,  4, CH3       , TIM4    ), // TIM4_CH3
  //( 3, SAI     ,  1, CK1       , SAI1    ), // SAI1_CK1
#if defined(MICROPY_HW_I2C1_SCL)
  AF( 4, I2C     ,  1, SCL       , I2C1    ), // I2C1_SCL
#endif
  //( 5, DFSDM   ,  1, CKOUT     , DFSDM1  ), // DFSDM1_CKOUT
  //( 6, DFSDM   ,  1, DATIN6    , DFSDM1  ), // DFSDM1_DATIN6
  //( 8, SDMMC   ,  1,  CKIN     , SDMMC1  ), // SDMMC1_ CKIN
#if defined(MICROPY_HW_CAN1_TX)
  AF( 9, CAN     ,  1, RX        , CAN1    ), // CAN1_RX
#endif
  //(10, DCMI    ,  0, D6        , DCMI    ), // DCMI_D6
  //(11, LCD     ,  0, B1        , LCD     ), // LCD_B1
  //(12, SDMMC   ,  1, D4        , SDMMC1  ), // SDMMC1_D4
  //(13, SAI     ,  1, MCLK_A    , SAI1    ), // SAI1_MCLK_A
  AF(14, TIM     , 16, CH1       , TIM16   ), // TIM16_CH1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B8_obj = PIN(B, 8, pin_B8_af, 0, 0);

const pin_af_obj_t pin_B9_af[] = {
  //( 1, IR      ,  0, OUT       , IR      ), // IR_OUT
  AF( 2, TIM     ,  4, CH4       , TIM4    ), // TIM4_CH4
  //( 3, SAI     ,  1, D2        , SAI1    ), // SAI1_D2
#if defined(MICROPY_HW_I2C1_SCL)
  AF( 4, I2C     ,  1, SDA       , I2C1    ), // I2C1_SDA
#endif
#if defined(MICROPY_HW_SPI2_SCK)
  AF( 5, SPI     ,  2, NSS       , SPI2    ), // SPI2_NSS
#endif
  //( 6, DFSDM   ,  1, CKIN6     , DFSDM1  ), // DFSDM1_CKIN6
  //( 8, SDMMC   ,  1, CDIR      , SDMMC1  ), // SDMMC1_CDIR
#if defined(MICROPY_HW_CAN1_TX)
  AF( 9, CAN     ,  1, TX        , CAN1    ), // CAN1_TX
#endif
  //(10, DCMI    ,  0, D7        , DCMI    ), // DCMI_D7
  //(12, SDMMC   ,  1, D5        , SDMMC1  ), // SDMMC1_D5
  //(13, SAI     ,  1, FS_A      , SAI1    ), // SAI1_FS_A
  AF(14, TIM     , 17, CH1       , TIM17   ), // TIM17_CH1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B9_obj = PIN(B, 9, pin_B9_af, 0, 0);

const pin_af_obj_t pin_B10_af[] = {
  AF( 1, TIM     ,  2, CH3       , TIM2    ), // TIM2_CH3
#if defined(MICROPY_HW_I2C4_SCL)
  AF( 3, I2C     ,  4, SCL       , I2C4    ), // I2C4_SCL
#endif
#if defined(MICROPY_HW_I2C2_SCL)
  AF( 4, I2C     ,  2, SCL       , I2C2    ), // I2C2_SCL
#endif
#if defined(MICROPY_HW_SPI2_SCK)
  AF( 5, SPI     ,  2, SCK       , SPI2    ), // SPI2_SCK
#endif
  //( 6, DFSDM   ,  1, DATIN7    , DFSDM1  ), // DFSDM1_DATIN7
#if defined(MICROPY_HW_UART3_TX)
  AF( 7, USART   ,  3, TX        , USART3  ), // USART3_TX
#endif
  //( 8, LPUART  ,  1, RX        , LPUART1 ), // LPUART1_RX
  //( 9, TSC     ,  0, SYNC      , TSC     ), // TSC_SYNC
  //(10, OCTOSPIM,  0, P1_CLK    , OCTOSPIM), // OCTOSPIM_P1_CLK
  //(12, COMP    ,  1, OUT       , COMP1   ), // COMP1_OUT
  //(13, SAI     ,  1, SCK_A     , SAI1    ), // SAI1_SCK_A
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B10_obj = PIN(B, 10, pin_B10_af, 0, 0);

const pin_af_obj_t pin_B11_af[] = {
  AF( 1, TIM     ,  2, CH4       , TIM2    ), // TIM2_CH4
#if defined(MICROPY_HW_I2C4_SCL)
  AF( 3, I2C     ,  4, SDA       , I2C4    ), // I2C4_SDA
#endif
#if defined(MICROPY_HW_I2C2_SCL)
  AF( 4, I2C     ,  2, SDA       , I2C2    ), // I2C2_SDA
#endif
  //( 6, DFSDM   ,  1, CKIN7     , DFSDM1  ), // DFSDM1_CKIN7
#if defined(MICROPY_HW_UART3_TX)
  AF( 7, USART   ,  3, RX        , USART3  ), // USART3_RX
#endif
  //( 8, LPUART  ,  1, TX        , LPUART1 ), // LPUART1_TX
  //(10, OCTOSPIM,  0, P1_NCS    , OCTOSPIM), // OCTOSPIM_P1_NCS
  //(11, DSI     ,  0, TE        , DSI     ), // DSI_TE
  //(12, COMP    ,  2, OUT       , COMP2   ), // COMP2_OUT
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B11_obj = PIN(B, 11, pin_B11_af, 0, 0);

const pin_af_obj_t pin_B12_af[] = {
  AF( 1, TIM     ,  1, BKIN      , TIM1    ), // TIM1_BKIN
  AF( 3, TIM     ,  1, BKIN      , TIM1    ), // TIM1_BKIN
  //( 4, I2C     ,  2, SMBA      , I2C2    ), // I2C2_SMBA
#if defined(MICROPY_HW_SPI2_SCK)
  AF( 5, SPI     ,  2, NSS       , SPI2    ), // SPI2_NSS
#endif
  //( 6, DFSDM   ,  1, DATIN1    , DFSDM1  ), // DFSDM1_DATIN1
#if defined(MICROPY_HW_UART3_TX)
  AF( 7, USART   ,  3, CK        , USART3  ), // USART3_CK
#endif
  //( 8, LPUART  ,  1, RTS_DE    , LPUART1 ), // LPUART1_RTS_DE
  //( 9, TSC     ,  0, G1_IO1    , TSC     ), // TSC_G1_IO1
  //(13, SAI     ,  2, FS_A      , SAI2    ), // SAI2_FS_A
  AF(14, TIM     , 15, BKIN      , TIM15   ), // TIM15_BKIN
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B12_obj = PIN(B, 12, pin_B12_af, 0, 0);

const pin_af_obj_t pin_B13_af[] = {
  AF( 1, TIM     ,  1, CH1N      , TIM1    ), // TIM1_CH1N
#if defined(MICROPY_HW_I2C2_SCL)
  AF( 4, I2C     ,  2, SCL       , I2C2    ), // I2C2_SCL
#endif
#if defined(MICROPY_HW_SPI2_SCK)
  AF( 5, SPI     ,  2, SCK       , SPI2    ), // SPI2_SCK
#endif
  //( 6, DFSDM   ,  1, CKIN1     , DFSDM1  ), // DFSDM1_CKIN1
  //( 7, USART   ,  3, CTS_NSS   , USART3  ), // USART3_CTS_NSS
  //( 8, LPUART  ,  1, CTS       , LPUART1 ), // LPUART1_CTS
  //( 9, TSC     ,  0, G1_IO2    , TSC     ), // TSC_G1_IO2
  //(13, SAI     ,  2, SCK_A     , SAI2    ), // SAI2_SCK_A
  AF(14, TIM     , 15, CH1N      , TIM15   ), // TIM15_CH1N
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B13_obj = PIN(B, 13, pin_B13_af, 0, 0);

const pin_af_obj_t pin_B14_af[] = {
  AF( 1, TIM     ,  1, CH2N      , TIM1    ), // TIM1_CH2N
  AF( 3, TIM     ,  8, CH2N      , TIM8    ), // TIM8_CH2N
#if defined(MICROPY_HW_I2C2_SCL)
  AF( 4, I2C     ,  2, SDA       , I2C2    ), // I2C2_SDA
#endif
#if defined(MICROPY_HW_SPI2_SCK)
  AF( 5, SPI     ,  2, MISO      , SPI2    ), // SPI2_MISO
#endif
  //( 6, DFSDM   ,  1, DATIN2    , DFSDM1  ), // DFSDM1_DATIN2
  //( 7, USART   ,  3, RTS_DE    , USART3  ), // USART3_RTS_DE
  //( 9, TSC     ,  0, G1_IO3    , TSC     ), // TSC_G1_IO3
  //(13, SAI     ,  2, MCLK_A    , SAI2    ), // SAI2_MCLK_A
  AF(14, TIM     , 15, CH1       , TIM15   ), // TIM15_CH1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B14_obj = PIN(B, 14, pin_B14_af, 0, 0);

const pin_af_obj_t pin_B15_af[] = {
  //( 0, RTC     ,  0, REFIN     , RTC     ), // RTC_REFIN
  AF( 1, TIM     ,  1, CH3N      , TIM1    ), // TIM1_CH3N
  AF( 3, TIM     ,  8, CH3N      , TIM8    ), // TIM8_CH3N
#if defined(MICROPY_HW_SPI2_SCK)
  AF( 5, SPI     ,  2, MOSI      , SPI2    ), // SPI2_MOSI
#endif
  //( 6, DFSDM   ,  1, CKIN2     , DFSDM1  ), // DFSDM1_CKIN2
  //( 9, TSC     ,  0, G1_IO4    , TSC     ), // TSC_G1_IO4
  //(13, SAI     ,  2, SD_A      , SAI2    ), // SAI2_SD_A
  AF(14, TIM     , 15, CH2       , TIM15   ), // TIM15_CH2
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_B15_obj = PIN(B, 15, pin_B15_af, 0, 0);

const pin_af_obj_t pin_C0_af[] = {
  //( 1, LPTIM   ,  1, IN1       , LPTIM1  ), // LPTIM1_IN1
#if defined(MICROPY_HW_I2C3_SCL)
  AF( 4, I2C     ,  3, SCL       , I2C3    ), // I2C3_SCL
#endif
  //( 6, DFSDM   ,  1, DATIN4    , DFSDM1  ), // DFSDM1_DATIN4
  //( 8, LPUART  ,  1, RX        , LPUART1 ), // LPUART1_RX
  //(13, SAI     ,  2, FS_A      , SAI2    ), // SAI2_FS_A
  //(14, LPTIM   ,  2, IN1       , LPTIM2  ), // LPTIM2_IN1
  //(15, EVENTOUT ,  0,           , EVENTOUT ), // EVENTOUT 
};

const pin_obj_t pin_C0_obj = PIN(C, 0, pin_C0_af, PIN_ADC1, 1);

const pin_af_obj_t pin_C1_af[] = {
  //( 0, TRACED  ,  0,           , TRACED0 ), // TRACED0
  //( 1, LPTIM   ,  1, OUT       , LPTIM1  ), // LPTIM1_OUT
#if defined(MICROPY_HW_SPI2_SCK)
  AF( 3, SPI     ,  2, MOSI      , SPI2    ), // SPI2_MOSI
#endif
#if defined(MICROPY_HW_I2C3_SCL)
  AF( 4, I2C     ,  3, SDA       , I2C3    ), // I2C3_SDA
#endif
  //( 6, DFSDM   ,  1, CKIN4     , DFSDM1  ), // DFSDM1_CKIN4
  //( 8, LPUART  ,  1, TX        , LPUART1 ), // LPUART1_TX
  //(10, OCTOSPIM,  0, P1_IO4    , OCTOSPIM), // OCTOSPIM_P1_IO4
  //(13, SAI     ,  1, SD_A      , SAI1    ), // SAI1_SD_A
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_C1_obj = PIN(C, 1, pin_C1_af, PIN_ADC1, 2);

const pin_af_obj_t pin_C2_af[] = {
  //( 1, LPTIM   ,  1, IN2       , LPTIM1  ), // LPTIM1_IN2
#if defined(MICROPY_HW_SPI2_SCK)
  AF( 5, SPI     ,  2, MISO      , SPI2    ), // SPI2_MISO
#endif
  //( 6, DFSDM   ,  1, CKOUT     , DFSDM1  ), // DFSDM1_CKOUT
  //(10, OCTOSPIM,  0, P1_IO5    , OCTOSPIM), // OCTOSPIM_P1_IO5
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_C2_obj = PIN(C, 2, pin_C2_af, PIN_ADC1, 3);

const pin_af_obj_t pin_C3_af[] = {
  //( 1, LPTIM   ,  1, ETR       , LPTIM1  ), // LPTIM1_ETR
  //( 3, SAI     ,  1, D1        , SAI1    ), // SAI1_D1
#if defined(MICROPY_HW_SPI2_SCK)
  AF( 5, SPI     ,  2, MOSI      , SPI2    ), // SPI2_MOSI
#endif
  //(10, OCTOSPIM,  0, P1_IO6    , OCTOSPIM), // OCTOSPIM_P1_IO6
  //(13, SAI     ,  1, SD_A      , SAI1    ), // SAI1_SD_A
  //(14, LPTIM   ,  2, ETR       , LPTIM2  ), // LPTIM2_ETR
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_C3_obj = PIN(C, 3, pin_C3_af, PIN_ADC1, 4);

const pin_af_obj_t pin_C4_af[] = {
#if defined(MICROPY_HW_UART3_TX)
  AF( 7, USART   ,  3, TX        , USART3  ), // USART3_TX
#endif
  //(10, OCTOSPIM,  0, P1_IO7    , OCTOSPIM), // OCTOSPIM_P1_IO7
  //(15, EVENTOUT ,  0,           , EVENTOUT ), // EVENTOUT 
};

const pin_obj_t pin_C4_obj = PIN(C, 4, pin_C4_af, PIN_ADC1, 13);

const pin_af_obj_t pin_C5_af[] = {
  //( 3, SAI     ,  1, D3        , SAI1    ), // SAI1_D3
#if defined(MICROPY_HW_UART3_TX)
  AF( 7, USART   ,  3, RX        , USART3  ), // USART3_RX
#endif
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_C5_obj = PIN(C, 5, pin_C5_af, PIN_ADC1, 14);

const pin_af_obj_t pin_C6_af[] = {
  AF( 2, TIM     ,  3, CH1       , TIM3    ), // TIM3_CH1
  AF( 3, TIM     ,  8, CH1       , TIM8    ), // TIM8_CH1
  //( 6, DFSDM   ,  1, CKIN3     , DFSDM1  ), // DFSDM1_CKIN3
  //( 8, SDMMC   ,  1, D0DIR     , SDMMC1  ), // SDMMC1_D0DIR
  //( 9, TSC     ,  0, G4_IO1    , TSC     ), // TSC_G4_IO1
  //(10, DCMI    ,  0, D0        , DCMI    ), // DCMI_D0
  //(11, LCD     ,  0, R0        , LCD     ), // LCD_R0
  //(12, SDMMC   ,  1, D6        , SDMMC1  ), // SDMMC1_D6
  //(13, SAI     ,  2, MCLK_A    , SAI2    ), // SAI2_MCLK_A
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_C6_obj = PIN(C, 6, pin_C6_af, 0, 0);

const pin_af_obj_t pin_C7_af[] = {
  AF( 2, TIM     ,  3, CH2       , TIM3    ), // TIM3_CH2
  AF( 3, TIM     ,  8, CH2       , TIM8    ), // TIM8_CH2
  //( 6, DFSDM   ,  1, DATIN3    , DFSDM1  ), // DFSDM1_DATIN3
  //( 8, SDMMC   ,  1, D123DIR   , SDMMC1  ), // SDMMC1_D123DIR
  //( 9, TSC     ,  0, G4_IO2    , TSC     ), // TSC_G4_IO2
  //(10, DCMI    ,  0, D1        , DCMI    ), // DCMI_D1
  //(11, LCD     ,  0, R1        , LCD     ), // LCD_R1
  //(12, SDMMC   ,  1, D7        , SDMMC1  ), // SDMMC1_D7
  //(13, SAI     ,  2, MCLK_B    , SAI2    ), // SAI2_MCLK_B
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_C7_obj = PIN(C, 7, pin_C7_af, 0, 0);

const pin_af_obj_t pin_C8_af[] = {
  AF( 2, TIM     ,  3, CH3       , TIM3    ), // TIM3_CH3
  AF( 3, TIM     ,  8, CH3       , TIM8    ), // TIM8_CH3
  //( 9, TSC     ,  0, G4_IO3    , TSC     ), // TSC_G4_IO3
  //(10, DCMI    ,  0, D2        , DCMI    ), // DCMI_D2
#if defined(MICROPY_HW_SDMMC1_CK)
  AF(12, SDMMC   ,  1, D0        , SDMMC1  ), // SDMMC1_D0
#endif
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_C8_obj = PIN(C, 8, pin_C8_af, 0, 0);

const pin_af_obj_t pin_C9_af[] = {
  //( 0, TRACED  ,  0,           , TRACED0 ), // TRACED0
  //( 1, TIM     ,  8, BKIN2     , TIM8    ), // TIM8_BKIN2
  AF( 2, TIM     ,  3, CH4       , TIM3    ), // TIM3_CH4
  AF( 3, TIM     ,  8, CH4       , TIM8    ), // TIM8_CH4
  //( 4, DCMI    ,  0, D3        , DCMI    ), // DCMI_D3
#if defined(MICROPY_HW_I2C3_SCL)
  AF( 6, I2C     ,  3, SDA       , I2C3    ), // I2C3_SDA
#endif
  //( 9, TSC     ,  0, G4_IO4    , TSC     ), // TSC_G4_IO4
  //(10, OTG     ,  0, FS_NOE    , OTG     ), // OTG_FS_NOE
#if defined(MICROPY_HW_SDMMC1_CK)
  AF(12, SDMMC   ,  1, D1        , SDMMC1  ), // SDMMC1_D1
#endif
  //(13, SAI     ,  2, EXTCLK    , SAI2    ), // SAI2_EXTCLK
  //(14, TIM     ,  8, BKIN2     , TIM8    ), // TIM8_BKIN2
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_C9_obj = PIN(C, 9, pin_C9_af, 0, 0);

const pin_af_obj_t pin_C10_af[] = {
  //( 0, TRACED  ,  1,           , TRACED1 ), // TRACED1
#if defined(MICROPY_HW_SPI3_SCK)
  AF( 6, SPI     ,  3, SCK       , SPI3    ), // SPI3_SCK
#endif
#if defined(MICROPY_HW_UART3_TX)
  AF( 7, USART   ,  3, TX        , USART3  ), // USART3_TX
#endif
#if defined(MICROPY_HW_UART4_TX)
  AF( 8, UART    ,  4, TX        , UART4   ), // UART4_TX
#endif
  //( 9, TSC     ,  0, G3_IO2    , TSC     ), // TSC_G3_IO2
  //(10, DCMI    ,  0, D8        , DCMI    ), // DCMI_D8
#if defined(MICROPY_HW_SDMMC1_CK)
  AF(12, SDMMC   ,  1, D2        , SDMMC1  ), // SDMMC1_D2
#endif
  //(13, SAI     ,  2, SCK_B     , SAI2    ), // SAI2_SCK_B
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_C10_obj = PIN(C, 10, pin_C10_af, 0, 0);

const pin_af_obj_t pin_C11_af[] = {
  //( 4, DCMI    ,  0, D2        , DCMI    ), // DCMI_D2
  //( 5, OCTOSPIM,  0, P1_NCS    , OCTOSPIM), // OCTOSPIM_P1_NCS
#if defined(MICROPY_HW_SPI3_SCK)
  AF( 6, SPI     ,  3, MISO      , SPI3    ), // SPI3_MISO
#endif
#if defined(MICROPY_HW_UART3_TX)
  AF( 7, USART   ,  3, RX        , USART3  ), // USART3_RX
#endif
#if defined(MICROPY_HW_UART4_TX)
  AF( 8, UART    ,  4, RX        , UART4   ), // UART4_RX
#endif
  //( 9, TSC     ,  0, G3_IO3    , TSC     ), // TSC_G3_IO3
  //(10, DCMI    ,  0, D4        , DCMI    ), // DCMI_D4
#if defined(MICROPY_HW_SDMMC1_CK)
  AF(12, SDMMC   ,  1, D3        , SDMMC1  ), // SDMMC1_D3
#endif
  //(13, SAI     ,  2, MCLK_B    , SAI2    ), // SAI2_MCLK_B
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_C11_obj = PIN(C, 11, pin_C11_af, 0, 0);

const pin_af_obj_t pin_C12_af[] = {
  //( 0, TRACED  ,  3,           , TRACED3 ), // TRACED3
#if defined(MICROPY_HW_SPI3_SCK)
  AF( 6, SPI     ,  3, MOSI      , SPI3    ), // SPI3_MOSI
#endif
#if defined(MICROPY_HW_UART3_TX)
  AF( 7, USART   ,  3, CK        , USART3  ), // USART3_CK
#endif
#if defined(MICROPY_HW_UART5_TX)
  AF( 8, UART    ,  5, TX        , UART5   ), // UART5_TX
#endif
  //( 9, TSC     ,  0, G3_IO4    , TSC     ), // TSC_G3_IO4
  //(10, DCMI    ,  0, D9        , DCMI    ), // DCMI_D9
#if defined(MICROPY_HW_SDMMC1_CK)
  AF(12, SDMMC   ,  1, CK        , SDMMC1  ), // SDMMC1_CK
#endif
  //(13, SAI     ,  2, SD_B      , SAI2    ), // SAI2_SD_B
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_C12_obj = PIN(C, 12, pin_C12_af, 0, 0);

// const pin_af_obj_t pin_C13_af[] = {
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_C13_obj = PIN(C, 13, NULL, 0, 0);

// const pin_af_obj_t pin_C14_af[] = {
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_C14_obj = PIN(C, 14, NULL, 0, 0);

// const pin_af_obj_t pin_C15_af[] = {
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_C15_obj = PIN(C, 15, NULL, 0, 0);

const pin_af_obj_t pin_D0_af[] = {
#if defined(MICROPY_HW_SPI2_SCK)
  AF( 5, SPI     ,  2, NSS       , SPI2    ), // SPI2_NSS
#endif
  //( 6, DFSDM   ,  1, DATIN7    , DFSDM1  ), // DFSDM1_DATIN7
#if defined(MICROPY_HW_CAN1_TX)
  AF( 9, CAN     ,  1, RX        , CAN1    ), // CAN1_RX
#endif
  //(11, LCD     ,  0, B4        , LCD     ), // LCD_B4
  //(12, FMC     ,  0, D2        , FMC     ), // FMC_D2
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_D0_obj = PIN(D, 0, pin_D0_af, 0, 0);

const pin_af_obj_t pin_D1_af[] = {
#if defined(MICROPY_HW_SPI2_SCK)
  AF( 5, SPI     ,  2, SCK       , SPI2    ), // SPI2_SCK
#endif
  //( 6, DFSDM   ,  1, CKIN7     , DFSDM1  ), // DFSDM1_CKIN7
#if defined(MICROPY_HW_CAN1_TX)
  AF( 9, CAN     ,  1, TX        , CAN1    ), // CAN1_TX
#endif
  //(11, LCD     ,  0, B5        , LCD     ), // LCD_B5
  //(12, FMC     ,  0, D3        , FMC     ), // FMC_D3
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_D1_obj = PIN(D, 1, pin_D1_af, 0, 0);

const pin_af_obj_t pin_D2_af[] = {
  //( 0, TRACED  ,  2,           , TRACED2 ), // TRACED2
  AF( 2, TIM     ,  3, ETR       , TIM3    ), // TIM3_ETR
  //( 7, USART   ,  3, RTS_DE    , USART3  ), // USART3_RTS_DE
#if defined(MICROPY_HW_UART5_TX)
  AF( 8, UART    ,  5, RX        , UART5   ), // UART5_RX
#endif
  //( 9, TSC     ,  0, SYNC      , TSC     ), // TSC_SYNC
  //(10, DCMI    ,  0, D11       , DCMI    ), // DCMI_D11
#if defined(MICROPY_HW_SDMMC1_CK)
  AF(12, SDMMC   ,  1, CMD       , SDMMC1  ), // SDMMC1_CMD
#endif
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_D2_obj = PIN(D, 2, pin_D2_af, 0, 0);

const pin_af_obj_t pin_D3_af[] = {
#if defined(MICROPY_HW_SPI2_SCK)
  AF( 3, SPI     ,  2, SCK       , SPI2    ), // SPI2_SCK
#endif
  //( 4, DCMI    ,  0, D5        , DCMI    ), // DCMI_D5
#if defined(MICROPY_HW_SPI2_SCK)
  AF( 5, SPI     ,  2, MISO      , SPI2    ), // SPI2_MISO
#endif
  //( 6, DFSDM   ,  1, DATIN0    , DFSDM1  ), // DFSDM1_DATIN0
  //( 7, USART   ,  2, CTS_NSS   , USART2  ), // USART2_CTS_NSS
  //(10, OCTOSPIM,  0, P2_NCS    , OCTOSPIM), // OCTOSPIM_P2_NCS
  //(11, LCD     ,  0, CLK       , LCD     ), // LCD_CLK
  //(12, FMC     ,  0, CLK       , FMC     ), // FMC_CLK
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_D3_obj = PIN(D, 3, pin_D3_af, 0, 0);

const pin_af_obj_t pin_D4_af[] = {
#if defined(MICROPY_HW_SPI2_SCK)
  AF( 5, SPI     ,  2, MOSI      , SPI2    ), // SPI2_MOSI
#endif
  //( 6, DFSDM   ,  1, CKIN0     , DFSDM1  ), // DFSDM1_CKIN0
  //( 7, USART   ,  2, RTS_DE    , USART2  ), // USART2_RTS_DE
  //(10, OCTOSPIM,  0, P1_IO4    , OCTOSPIM), // OCTOSPIM_P1_IO4
  //(12, FMC     ,  0, NOE       , FMC     ), // FMC_NOE
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_D4_obj = PIN(D, 4, pin_D4_af, 0, 0);

const pin_af_obj_t pin_D5_af[] = {
#if defined(MICROPY_HW_UART2_TX)
  AF( 7, USART   ,  2, TX        , USART2  ), // USART2_TX
#endif
  //(10, OCTOSPIM,  0, P1_IO5    , OCTOSPIM), // OCTOSPIM_P1_IO5
  //(12, FMC     ,  0, NWE       , FMC     ), // FMC_NWE
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_D5_obj = PIN(D, 5, pin_D5_af, 0, 0);

const pin_af_obj_t pin_D6_af[] = {
  //( 3, SAI     ,  1, D1        , SAI1    ), // SAI1_D1
  //( 4, DCMI    ,  0, D10       , DCMI    ), // DCMI_D10
#if defined(MICROPY_HW_SPI3_SCK)
  AF( 5, SPI     ,  3, MOSI      , SPI3    ), // SPI3_MOSI
#endif
  //( 6, DFSDM   ,  1, DATIN1    , DFSDM1  ), // DFSDM1_DATIN1
#if defined(MICROPY_HW_UART2_TX)
  AF( 7, USART   ,  2, RX        , USART2  ), // USART2_RX
#endif
  //(10, OCTOSPIM,  0, P1_IO6    , OCTOSPIM), // OCTOSPIM_P1_IO6
  //(11, LCD     ,  0, DE        , LCD     ), // LCD_DE
  //(12, FMC     ,  0, NWAIT     , FMC     ), // FMC_NWAIT
  //(13, SAI     ,  1, SD_A      , SAI1    ), // SAI1_SD_A
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_D6_obj = PIN(D, 6, pin_D6_af, 0, 0);

const pin_af_obj_t pin_D7_af[] = {
  //( 6, DFSDM   ,  1, CKIN1     , DFSDM1  ), // DFSDM1_CKIN1
#if defined(MICROPY_HW_UART2_TX)
  AF( 7, USART   ,  2, CK        , USART2  ), // USART2_CK
#endif
  //(10, OCTOSPIM,  0, P1_IO7    , OCTOSPIM), // OCTOSPIM_P1_IO7
  //(12, FMC     ,  0, NCE       , FMC     ), // FMC_NCE
  //(12, FMC     ,  0, NE1       , FMC     ), // FMC_NE1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_D7_obj = PIN(D, 7, pin_D7_af, 0, 0);

const pin_af_obj_t pin_D8_af[] = {
#if defined(MICROPY_HW_UART3_TX)
  AF( 7, USART   ,  3, TX        , USART3  ), // USART3_TX
#endif
  //(10, DCMI    ,  0, HSYNC     , DCMI    ), // DCMI_HSYNC
  //(11, LCD     ,  0, R3        , LCD     ), // LCD_R3
  //(12, FMC     ,  0, D13       , FMC     ), // FMC_D13
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_D8_obj = PIN(D, 8, pin_D8_af, 0, 0);

const pin_af_obj_t pin_D9_af[] = {
#if defined(MICROPY_HW_UART3_TX)
  AF( 7, USART   ,  3, RX        , USART3  ), // USART3_RX
#endif
  //(10, DCMI    ,  0, PIXCLK    , DCMI    ), // DCMI_PIXCLK
  //(11, LCD     ,  0, R4        , LCD     ), // LCD_R4
  //(12, FMC     ,  0, D14       , FMC     ), // FMC_D14
  //(13, SAI     ,  2, MCLK_A    , SAI2    ), // SAI2_MCLK_A
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_D9_obj = PIN(D, 9, pin_D9_af, 0, 0);

const pin_af_obj_t pin_D10_af[] = {
#if defined(MICROPY_HW_UART3_TX)
  AF( 7, USART   ,  3, CK        , USART3  ), // USART3_CK
#endif
  //( 9, TSC     ,  0, G6_IO1    , TSC     ), // TSC_G6_IO1
  //(11, LCD     ,  0, R5        , LCD     ), // LCD_R5
  //(12, FMC     ,  0, D15       , FMC     ), // FMC_D15
  //(13, SAI     ,  2, SCK_A     , SAI2    ), // SAI2_SCK_A
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_D10_obj = PIN(D, 10, pin_D10_af, 0, 0);

// const pin_af_obj_t pin_D11_af[] = {
  //( 4, I2C     ,  4, SMBA      , I2C4    ), // I2C4_SMBA
  //( 7, USART   ,  3, CTS_NSS   , USART3  ), // USART3_CTS_NSS
  //( 9, TSC     ,  0, G6_IO2    , TSC     ), // TSC_G6_IO2
  //(11, LCD     ,  0, R6        , LCD     ), // LCD_R6
  //(12, FMC     ,  0, A16       , FMC     ), // FMC_A16
  //(13, SAI     ,  2, SD_A      , SAI2    ), // SAI2_SD_A
  //(14, LPTIM   ,  2, ETR       , LPTIM2  ), // LPTIM2_ETR
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_D11_obj = PIN(D, 11, NULL, 0, 0);

const pin_af_obj_t pin_D12_af[] = {
  AF( 2, TIM     ,  4, CH1       , TIM4    ), // TIM4_CH1
#if defined(MICROPY_HW_I2C4_SCL)
  AF( 4, I2C     ,  4, SCL       , I2C4    ), // I2C4_SCL
#endif
  //( 7, USART   ,  3, RTS_DE    , USART3  ), // USART3_RTS_DE
  //( 9, TSC     ,  0, G6_IO3    , TSC     ), // TSC_G6_IO3
  //(11, LCD     ,  0, R7        , LCD     ), // LCD_R7
  //(12, FMC     ,  0, A17       , FMC     ), // FMC_A17
  //(13, SAI     ,  2, FS_A      , SAI2    ), // SAI2_FS_A
  //(14, LPTIM   ,  2, IN1       , LPTIM2  ), // LPTIM2_IN1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_D12_obj = PIN(D, 12, pin_D12_af, 0, 0);

const pin_af_obj_t pin_D13_af[] = {
  AF( 2, TIM     ,  4, CH2       , TIM4    ), // TIM4_CH2
#if defined(MICROPY_HW_I2C4_SCL)
  AF( 4, I2C     ,  4, SDA       , I2C4    ), // I2C4_SDA
#endif
  //( 9, TSC     ,  0, G6_IO4    , TSC     ), // TSC_G6_IO4
  //(12, FMC     ,  0, A18       , FMC     ), // FMC_A18
  //(14, LPTIM   ,  2, OUT       , LPTIM2  ), // LPTIM2_OUT
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_D13_obj = PIN(D, 13, pin_D13_af, 0, 0);

const pin_af_obj_t pin_D14_af[] = {
  AF( 2, TIM     ,  4, CH3       , TIM4    ), // TIM4_CH3
  //(11, LCD     ,  0, B2        , LCD     ), // LCD_B2
  //(12, FMC     ,  0, D0        , FMC     ), // FMC_D0
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_D14_obj = PIN(D, 14, pin_D14_af, 0, 0);

const pin_af_obj_t pin_D15_af[] = {
  AF( 2, TIM     ,  4, CH4       , TIM4    ), // TIM4_CH4
  //(11, LCD     ,  0, B3        , LCD     ), // LCD_B3
  //(12, FMC     ,  0, D1        , FMC     ), // FMC_D1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_D15_obj = PIN(D, 15, pin_D15_af, 0, 0);

const pin_af_obj_t pin_E0_af[] = {
  AF( 2, TIM     ,  4, ETR       , TIM4    ), // TIM4_ETR
  //(10, DCMI    ,  0, D2        , DCMI    ), // DCMI_D2
  //(11, LCD     ,  0, HSYNC     , LCD     ), // LCD_HSYNC
  //(12, FMC     ,  0, NBL0      , FMC     ), // FMC_NBL0
  AF(14, TIM     , 16, CH1       , TIM16   ), // TIM16_CH1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_E0_obj = PIN(E, 0, pin_E0_af, 0, 0);

const pin_af_obj_t pin_E1_af[] = {
  //(10, DCMI    ,  0, D3        , DCMI    ), // DCMI_D3
  //(11, LCD     ,  0, VSYNC     , LCD     ), // LCD_VSYNC
  //(12, FMC     ,  0, NBL1      , FMC     ), // FMC_NBL1
  AF(14, TIM     , 17, CH1       , TIM17   ), // TIM17_CH1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_E1_obj = PIN(E, 1, pin_E1_af, 0, 0);

const pin_af_obj_t pin_E2_af[] = {
  //( 0, TRACECK ,  0,           , TRACECK ), // TRACECK
  AF( 2, TIM     ,  3, ETR       , TIM3    ), // TIM3_ETR
  //( 3, SAI     ,  1, CK1       , SAI1    ), // SAI1_CK1
  //( 9, TSC     ,  0, G7_IO1    , TSC     ), // TSC_G7_IO1
  //(11, LCD     ,  0, R0        , LCD     ), // LCD_R0
  //(12, FMC     ,  0, A23       , FMC     ), // FMC_A23
  //(13, SAI     ,  1, MCLK_A    , SAI1    ), // SAI1_MCLK_A
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_E2_obj = PIN(E, 2, pin_E2_af, 0, 0);

const pin_af_obj_t pin_E3_af[] = {
  //( 0, TRACED  ,  0,           , TRACED0 ), // TRACED0
  AF( 2, TIM     ,  3, CH1       , TIM3    ), // TIM3_CH1
  //( 3, OCTOSPIM,  0, P1_DQS    , OCTOSPIM), // OCTOSPIM_P1_DQS
  //( 9, TSC     ,  0, G7_IO2    , TSC     ), // TSC_G7_IO2
  //(11, LCD     ,  0, R1        , LCD     ), // LCD_R1
  //(12, FMC     ,  0, A19       , FMC     ), // FMC_A19
  //(13, SAI     ,  1, SD_B      , SAI1    ), // SAI1_SD_B
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_E3_obj = PIN(E, 3, pin_E3_af, 0, 0);

const pin_af_obj_t pin_E4_af[] = {
  //( 0, TRACED  ,  1,           , TRACED1 ), // TRACED1
  AF( 2, TIM     ,  3, CH2       , TIM3    ), // TIM3_CH2
  //( 3, SAI     ,  1, D2        , SAI1    ), // SAI1_D2
  //( 6, DFSDM   ,  1, DATIN3    , DFSDM1  ), // DFSDM1_DATIN3
  //( 9, TSC     ,  0, G7_IO3    , TSC     ), // TSC_G7_IO3
  //(10, DCMI    ,  0, D4        , DCMI    ), // DCMI_D4
  //(11, LCD     ,  0, B0        , LCD     ), // LCD_B0
  //(12, FMC     ,  0, A20       , FMC     ), // FMC_A20
  //(13, SAI     ,  1, FS_A      , SAI1    ), // SAI1_FS_A
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_E4_obj = PIN(E, 4, pin_E4_af, 0, 0);

const pin_af_obj_t pin_E5_af[] = {
  //( 0, TRACED  ,  2,           , TRACED2 ), // TRACED2
  AF( 2, TIM     ,  3, CH3       , TIM3    ), // TIM3_CH3
  //( 3, SAI     ,  1, CK2       , SAI1    ), // SAI1_CK2
  //( 6, DFSDM   ,  1, CKIN3     , DFSDM1  ), // DFSDM1_CKIN3
  //( 9, TSC     ,  0, G7_IO4    , TSC     ), // TSC_G7_IO4
  //(10, DCMI    ,  0, D6        , DCMI    ), // DCMI_D6
  //(11, LCD     ,  0, G0        , LCD     ), // LCD_G0
  //(12, FMC     ,  0, A21       , FMC     ), // FMC_A21
  //(13, SAI     ,  1, SCK_A     , SAI1    ), // SAI1_SCK_A
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_E5_obj = PIN(E, 5, pin_E5_af, 0, 0);

const pin_af_obj_t pin_E6_af[] = {
  //( 0, TRACED  ,  3,           , TRACED3 ), // TRACED3
  AF( 2, TIM     ,  3, CH4       , TIM3    ), // TIM3_CH4
  //( 3, SAI     ,  1, D1        , SAI1    ), // SAI1_D1
  //(10, DCMI    ,  0, D7        , DCMI    ), // DCMI_D7
  //(11, LCD     ,  0, G1        , LCD     ), // LCD_G1
  //(12, FMC     ,  0, A22       , FMC     ), // FMC_A22
  //(13, SAI     ,  1, SD_A      , SAI1    ), // SAI1_SD_A
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_E6_obj = PIN(E, 6, pin_E6_af, 0, 0);

const pin_af_obj_t pin_E7_af[] = {
  AF( 1, TIM     ,  1, ETR       , TIM1    ), // TIM1_ETR
  //( 6, DFSDM   ,  1, DATIN2    , DFSDM1  ), // DFSDM1_DATIN2
  //(11, LCD     ,  0, B6        , LCD     ), // LCD_B6
  //(12, FMC     ,  0, D4        , FMC     ), // FMC_D4
  //(13, SAI     ,  1, SD_B      , SAI1    ), // SAI1_SD_B
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_E7_obj = PIN(E, 7, pin_E7_af, 0, 0);

const pin_af_obj_t pin_E8_af[] = {
  AF( 1, TIM     ,  1, CH1N      , TIM1    ), // TIM1_CH1N
  //( 6, DFSDM   ,  1, CKIN2     , DFSDM1  ), // DFSDM1_CKIN2
  //(11, LCD     ,  0, B7        , LCD     ), // LCD_B7
  //(12, FMC     ,  0, D5        , FMC     ), // FMC_D5
  //(13, SAI     ,  1, SCK_B     , SAI1    ), // SAI1_SCK_B
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_E8_obj = PIN(E, 8, pin_E8_af, 0, 0);

const pin_af_obj_t pin_E9_af[] = {
  AF( 1, TIM     ,  1, CH1       , TIM1    ), // TIM1_CH1
  //( 6, DFSDM   ,  1, CKOUT     , DFSDM1  ), // DFSDM1_CKOUT
  //(11, LCD     ,  0, G2        , LCD     ), // LCD_G2
  //(12, FMC     ,  0, D6        , FMC     ), // FMC_D6
  //(13, SAI     ,  1, FS_B      , SAI1    ), // SAI1_FS_B
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_E9_obj = PIN(E, 9, pin_E9_af, 0, 0);

const pin_af_obj_t pin_E10_af[] = {
  AF( 1, TIM     ,  1, CH2N      , TIM1    ), // TIM1_CH2N
  //( 6, DFSDM   ,  1, DATIN4    , DFSDM1  ), // DFSDM1_DATIN4
  //( 9, TSC     ,  0, G5_IO1    , TSC     ), // TSC_G5_IO1
  //(10, OCTOSPIM,  0, P1_CLK    , OCTOSPIM), // OCTOSPIM_P1_CLK
  //(11, LCD     ,  0, G3        , LCD     ), // LCD_G3
  //(12, FMC     ,  0, D7        , FMC     ), // FMC_D7
  //(13, SAI     ,  1, MCLK_B    , SAI1    ), // SAI1_MCLK_B
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_E10_obj = PIN(E, 10, pin_E10_af, 0, 0);

const pin_af_obj_t pin_E11_af[] = {
  AF( 1, TIM     ,  1, CH2       , TIM1    ), // TIM1_CH2
  //( 6, DFSDM   ,  1, CKIN4     , DFSDM1  ), // DFSDM1_CKIN4
  //( 9, TSC     ,  0, G5_IO2    , TSC     ), // TSC_G5_IO2
  //(10, OCTOSPIM,  0, P1_NCS    , OCTOSPIM), // OCTOSPIM_P1_NCS
  //(11, LCD     ,  0, G4        , LCD     ), // LCD_G4
  //(12, FMC     ,  0, D8        , FMC     ), // FMC_D8
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_E11_obj = PIN(E, 11, pin_E11_af, 0, 0);

const pin_af_obj_t pin_E12_af[] = {
  AF( 1, TIM     ,  1, CH3N      , TIM1    ), // TIM1_CH3N
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, NSS       , SPI1    ), // SPI1_NSS
#endif
  //( 6, DFSDM   ,  1, DATIN5    , DFSDM1  ), // DFSDM1_DATIN5
  //( 9, TSC     ,  0, G5_IO3    , TSC     ), // TSC_G5_IO3
  //(10, OCTOSPIM,  0, 1_IO0     , OCTOSPIM), // OCTOSPIM_1_IO0
  //(11, LCD     ,  0, G5        , LCD     ), // LCD_G5
  //(12, FMC     ,  0, D9        , FMC     ), // FMC_D9
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_E12_obj = PIN(E, 12, pin_E12_af, 0, 0);

const pin_af_obj_t pin_E13_af[] = {
  AF( 1, TIM     ,  1, CH3       , TIM1    ), // TIM1_CH3
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, SCK       , SPI1    ), // SPI1_SCK
#endif
  //( 6, DFSDM   ,  1, CKIN5     , DFSDM1  ), // DFSDM1_CKIN5
  //( 9, TSC     ,  0, G5_IO4    , TSC     ), // TSC_G5_IO4
  //(10, OCTOSPIM,  0, P1_IO1    , OCTOSPIM), // OCTOSPIM_P1_IO1
  //(11, LCD     ,  0, G6        , LCD     ), // LCD_G6
  //(12, FMC     ,  0, D10       , FMC     ), // FMC_D10
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_E13_obj = PIN(E, 13, pin_E13_af, 0, 0);

const pin_af_obj_t pin_E14_af[] = {
  AF( 1, TIM     ,  1, CH4       , TIM1    ), // TIM1_CH4
  //( 2, TIM     ,  1, BKIN2     , TIM1    ), // TIM1_BKIN2
  //( 3, TIM     ,  1, BKIN2     , TIM1    ), // TIM1_BKIN2
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, MISO      , SPI1    ), // SPI1_MISO
#endif
  //(10, OCTOSPIM,  0, P1_IO2    , OCTOSPIM), // OCTOSPIM_P1_IO2
  //(11, LCD     ,  0, G7        , LCD     ), // LCD_G7
  //(12, FMC     ,  0, D11       , FMC     ), // FMC_D11
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_E14_obj = PIN(E, 14, pin_E14_af, 0, 0);

const pin_af_obj_t pin_E15_af[] = {
  AF( 1, TIM     ,  1, BKIN      , TIM1    ), // TIM1_BKIN
  AF( 3, TIM     ,  1, BKIN      , TIM1    ), // TIM1_BKIN
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, MOSI      , SPI1    ), // SPI1_MOSI
#endif
  //(10, OCTOSPIM,  0, P1_IO3    , OCTOSPIM), // OCTOSPIM_P1_IO3
  //(11, LCD     ,  0, R2        , LCD     ), // LCD_R2
  //(12, FMC     ,  0, D12       , FMC     ), // FMC_D12
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_E15_obj = PIN(E, 15, pin_E15_af, 0, 0);

const pin_af_obj_t pin_F0_af[] = {
#if defined(MICROPY_HW_I2C2_SCL)
  AF( 4, I2C     ,  2, SDA       , I2C2    ), // I2C2_SDA
#endif
  //( 5, OCTOSPIM,  0, P2_IO0    , OCTOSPIM), // OCTOSPIM_P2_IO0
  //(12, FMC     ,  0, A0        , FMC     ), // FMC_A0
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_F0_obj = PIN(F, 0, pin_F0_af, 0, 0);

const pin_af_obj_t pin_F1_af[] = {
#if defined(MICROPY_HW_I2C2_SCL)
  AF( 4, I2C     ,  2, SCL       , I2C2    ), // I2C2_SCL
#endif
  //( 5, OCTOSPIM,  0, P2_IO1    , OCTOSPIM), // OCTOSPIM_P2_IO1
  //(12, FMC     ,  0, A1        , FMC     ), // FMC_A1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_F1_obj = PIN(F, 1, pin_F1_af, 0, 0);

// const pin_af_obj_t pin_F2_af[] = {
  //( 4, I2C     ,  2, SMBA      , I2C2    ), // I2C2_SMBA
  //( 5, OCTOSPIM,  0, P2_IO2    , OCTOSPIM), // OCTOSPIM_P2_IO2
  //(12, FMC     ,  0, A2        , FMC     ), // FMC_A2
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_F2_obj = PIN(F, 2, NULL, 0, 0);

// const pin_af_obj_t pin_F3_af[] = {
  //( 5, OCTOSPIM,  0, P2_IO3    , OCTOSPIM), // OCTOSPIM_P2_IO3
  //(12, FMC     ,  0, A3        , FMC     ), // FMC_A3
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_F3_obj = PIN(F, 3, NULL, 0, 0);

// const pin_af_obj_t pin_F4_af[] = {
  //( 5, OCTOSPIM,  0, P2_CLK    , OCTOSPIM), // OCTOSPIM_P2_CLK
  //(12, FMC     ,  0, A4        , FMC     ), // FMC_A4
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_F4_obj = PIN(F, 4, NULL, 0, 0);

// const pin_af_obj_t pin_F5_af[] = {
  //(12, FMC     ,  0, A5        , FMC     ), // FMC_A5
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_F5_obj = PIN(F, 5, NULL, 0, 0);

const pin_af_obj_t pin_F6_af[] = {
  AF( 1, TIM     ,  5, ETR       , TIM5    ), // TIM5_ETR
  AF( 2, TIM     ,  5, CH1       , TIM5    ), // TIM5_CH1
  //(10, OCTOSPIM,  0, P1_IO3    , OCTOSPIM), // OCTOSPIM_P1_IO3
  //(13, SAI     ,  1, SD_B      , SAI1    ), // SAI1_SD_B
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_F6_obj = PIN(F, 6, pin_F6_af, 0, 0);

const pin_af_obj_t pin_F7_af[] = {
  AF( 2, TIM     ,  5, CH2       , TIM5    ), // TIM5_CH2
  //(10, OCTOSPIM,  0, P1_IO2    , OCTOSPIM), // OCTOSPIM_P1_IO2
  //(13, SAI     ,  1, MCLK_B    , SAI1    ), // SAI1_MCLK_B
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_F7_obj = PIN(F, 7, pin_F7_af, 0, 0);

const pin_af_obj_t pin_F8_af[] = {
  AF( 2, TIM     ,  5, CH3       , TIM5    ), // TIM5_CH3
  //(10, OCTOSPIM,  0, P1_IO0    , OCTOSPIM), // OCTOSPIM_P1_IO0
  //(13, SAI     ,  1, SCK_B     , SAI1    ), // SAI1_SCK_B
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_F8_obj = PIN(F, 8, pin_F8_af, 0, 0);

const pin_af_obj_t pin_F9_af[] = {
  AF( 2, TIM     ,  5, CH4       , TIM5    ), // TIM5_CH4
  //(10, OCTOSPIM,  0, P1_IO1    , OCTOSPIM), // OCTOSPIM_P1_IO1
  //(13, SAI     ,  1, FS_B      , SAI1    ), // SAI1_FS_B
  AF(14, TIM     , 15, CH1       , TIM15   ), // TIM15_CH1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_F9_obj = PIN(F, 9, pin_F9_af, 0, 0);

const pin_af_obj_t pin_F10_af[] = {
  //( 3, OCTOSPIM,  0, P1_CLK    , OCTOSPIM), // OCTOSPIM_P1_CLK
  //( 6, DFSDM   ,  1, CKOUT     , DFSDM1  ), // DFSDM1_CKOUT
  //(10, DCMI    ,  0, D11       , DCMI    ), // DCMI_D11
  //(13, SAI     ,  1, D3        , SAI1    ), // SAI1_D3
  AF(14, TIM     , 15, CH2       , TIM15   ), // TIM15_CH2
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_F10_obj = PIN(F, 10, pin_F10_af, 0, 0);

// const pin_af_obj_t pin_F11_af[] = {
  //( 9, LCD     ,  0, DE        , LCD     ), // LCD_DE
  //(10, DCMI    ,  0, D12       , DCMI    ), // DCMI_D12
  //(11, DSI     ,  0, TE        , DSI     ), // DSI_TE
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_F11_obj = PIN(F, 11, NULL, 0, 0);

// const pin_af_obj_t pin_F12_af[] = {
  //( 5, OCTOSPIM,  0, P2_DQS    , OCTOSPIM), // OCTOSPIM_P2_DQS
  //(11, LCD     ,  0, B0        , LCD     ), // LCD_B0
  //(12, FMC     ,  0, A6        , FMC     ), // FMC_A6
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_F12_obj = PIN(F, 12, NULL, 0, 0);

// const pin_af_obj_t pin_F13_af[] = {
  //( 4, I2C     ,  4, SMBA      , I2C4    ), // I2C4_SMBA
  //( 6, DFSDM   ,  1, DATIN6    , DFSDM1  ), // DFSDM1_DATIN6
  //(11, LCD     ,  0, B1        , LCD     ), // LCD_B1
  //(12, FMC     ,  0, A7        , FMC     ), // FMC_A7
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_F13_obj = PIN(F, 13, NULL, 0, 0);

const pin_af_obj_t pin_F14_af[] = {
#if defined(MICROPY_HW_I2C4_SCL)
  AF( 4, I2C     ,  4, SCL       , I2C4    ), // I2C4_SCL
#endif
  //( 6, DFSDM   ,  1, CKIN6     , DFSDM1  ), // DFSDM1_CKIN6
  //( 9, TSC     ,  0, G8_IO1    , TSC     ), // TSC_G8_IO1
  //(11, LCD     ,  0, G0        , LCD     ), // LCD_G0
  //(12, FMC     ,  0, A8        , FMC     ), // FMC_A8
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_F14_obj = PIN(F, 14, pin_F14_af, 0, 0);

const pin_af_obj_t pin_F15_af[] = {
#if defined(MICROPY_HW_I2C4_SCL)
  AF( 4, I2C     ,  4, SDA       , I2C4    ), // I2C4_SDA
#endif
  //( 9, TSC     ,  0, G8_IO2    , TSC     ), // TSC_G8_IO2
  //(11, LCD     ,  0, G1        , LCD     ), // LCD_G1
  //(12, FMC     ,  0, A9        , FMC     ), // FMC_A9
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_F15_obj = PIN(F, 15, pin_F15_af, 0, 0);

// const pin_af_obj_t pin_G0_af[] = {
  //( 5, OCTOSPIM,  0, P2_IO4    , OCTOSPIM), // OCTOSPIM_P2_IO4
  //( 9, TSC     ,  0, G8_IO3    , TSC     ), // TSC_G8_IO3
  //(12, FMC     ,  0, A10       , FMC     ), // FMC_A10
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_G0_obj = PIN(G, 0, NULL, 0, 0);

// const pin_af_obj_t pin_G1_af[] = {
  //( 5, OCTOSPIM,  0, P2_IO5    , OCTOSPIM), // OCTOSPIM_P2_IO5
  //( 9, TSC     ,  0, G8_IO4    , TSC     ), // TSC_G8_IO4
  //(12, FMC     ,  0, A11       , FMC     ), // FMC_A11
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_G1_obj = PIN(G, 1, NULL, 0, 0);

const pin_af_obj_t pin_G2_af[] = {
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, SCK       , SPI1    ), // SPI1_SCK
#endif
  //(12, FMC     ,  0, A12       , FMC     ), // FMC_A12
  //(13, SAI     ,  2, SCK_B     , SAI2    ), // SAI2_SCK_B
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_G2_obj = PIN(G, 2, pin_G2_af, 0, 0);

const pin_af_obj_t pin_G3_af[] = {
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, MISO      , SPI1    ), // SPI1_MISO
#endif
  //(12, FMC     ,  0, A13       , FMC     ), // FMC_A13
  //(13, SAI     ,  2, FS_B      , SAI2    ), // SAI2_FS_B
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_G3_obj = PIN(G, 3, pin_G3_af, 0, 0);

const pin_af_obj_t pin_G4_af[] = {
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, MOSI      , SPI1    ), // SPI1_MOSI
#endif
  //(12, FMC     ,  0, A14       , FMC     ), // FMC_A14
  //(13, SAI     ,  2, MCLK_B    , SAI2    ), // SAI2_MCLK_B
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_G4_obj = PIN(G, 4, pin_G4_af, 0, 0);

const pin_af_obj_t pin_G5_af[] = {
#if defined(MICROPY_HW_SPI1_SCK)
  AF( 5, SPI     ,  1, NSS       , SPI1    ), // SPI1_NSS
#endif
  //( 8, LPUART  ,  1, CTS       , LPUART1 ), // LPUART1_CTS
  //(12, FMC     ,  0, A15       , FMC     ), // FMC_A15
  //(13, SAI     ,  2, SD_B      , SAI2    ), // SAI2_SD_B
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_G5_obj = PIN(G, 5, pin_G5_af, 0, 0);

// const pin_af_obj_t pin_G6_af[] = {
  //( 3, OCTOSPIM,  0, P1_DQS    , OCTOSPIM), // OCTOSPIM_P1_DQS
  //( 4, I2C     ,  3, SMBA      , I2C3    ), // I2C3_SMBA
  //( 8, LPUART  ,  1, RTS_DE    , LPUART1 ), // LPUART1_RTS_DE
  //( 9, LCD     ,  0, R1        , LCD     ), // LCD_R1
  //(11, DSI     ,  0, TE        , DSI     ), // DSI_TE
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_G6_obj = PIN(G, 6, NULL, 0, 0);

const pin_af_obj_t pin_G7_af[] = {
  //( 3, SAI     ,  1, CK1       , SAI1    ), // SAI1_CK1
#if defined(MICROPY_HW_I2C3_SCL)
  AF( 4, I2C     ,  3, SCL       , I2C3    ), // I2C3_SCL
#endif
  //( 5, OCTOSPIM,  0, P2_DQS    , OCTOSPIM), // OCTOSPIM_P2_DQS
  //( 6, DFSDM   ,  1, CKOUT     , DFSDM1  ), // DFSDM1_CKOUT
  //( 8, LPUART  ,  1, TX        , LPUART1 ), // LPUART1_TX
  //(12, FMC     ,  0, INT       , FMC     ), // FMC_INT
  //(13, SAI     ,  1, MCLK_A    , SAI1    ), // SAI1_MCLK_A
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_G7_obj = PIN(G, 7, pin_G7_af, 0, 0);

const pin_af_obj_t pin_G8_af[] = {
#if defined(MICROPY_HW_I2C3_SCL)
  AF( 4, I2C     ,  3, SDA       , I2C3    ), // I2C3_SDA
#endif
  //( 8, LPUART  ,  1, RX        , LPUART1 ), // LPUART1_RX
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_G8_obj = PIN(G, 8, pin_G8_af, 0, 0);

const pin_af_obj_t pin_G9_af[] = {
  //( 5, OCTOSPIM,  0, P2_IO6    , OCTOSPIM), // OCTOSPIM_P2_IO6
#if defined(MICROPY_HW_SPI3_SCK)
  AF( 6, SPI     ,  3, SCK       , SPI3    ), // SPI3_SCK
#endif
#if defined(MICROPY_HW_UART1_TX)
  AF( 7, USART   ,  1, TX        , USART1  ), // USART1_TX
#endif
  //(12, FMC     ,  0, NCE       , FMC     ), // FMC_NCE
  //(12, FMC     ,  0, NE2       , FMC     ), // FMC_NE2
  //(13, SAI     ,  2, SCK_A     , SAI2    ), // SAI2_SCK_A
  AF(14, TIM     , 15, CH1N      , TIM15   ), // TIM15_CH1N
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_G9_obj = PIN(G, 9, pin_G9_af, 0, 0);

const pin_af_obj_t pin_G10_af[] = {
  //( 1, LPTIM   ,  1, IN1       , LPTIM1  ), // LPTIM1_IN1
  //( 5, OCTOSPIM,  0, P2_IO7    , OCTOSPIM), // OCTOSPIM_P2_IO7
#if defined(MICROPY_HW_SPI3_SCK)
  AF( 6, SPI     ,  3, MISO      , SPI3    ), // SPI3_MISO
#endif
#if defined(MICROPY_HW_UART1_TX)
  AF( 7, USART   ,  1, RX        , USART1  ), // USART1_RX
#endif
  //(12, FMC     ,  0, NE3       , FMC     ), // FMC_NE3
  //(13, SAI     ,  2, FS_A      , SAI2    ), // SAI2_FS_A
  AF(14, TIM     , 15, CH1       , TIM15   ), // TIM15_CH1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_G10_obj = PIN(G, 10, pin_G10_af, 0, 0);

const pin_af_obj_t pin_G11_af[] = {
  //( 1, LPTIM   ,  1, IN2       , LPTIM1  ), // LPTIM1_IN2
  //( 3, OCTOSPIM,  0, P1_IO5    , OCTOSPIM), // OCTOSPIM_P1_IO5
#if defined(MICROPY_HW_SPI3_SCK)
  AF( 6, SPI     ,  3, MOSI      , SPI3    ), // SPI3_MOSI
#endif
  //( 7, USART   ,  1, CTS_NSS   , USART1  ), // USART1_CTS_NSS
  //(13, SAI     ,  2, MCLK_A    , SAI2    ), // SAI2_MCLK_A
  AF(14, TIM     , 15, CH2       , TIM15   ), // TIM15_CH2
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_G11_obj = PIN(G, 11, pin_G11_af, 0, 0);

const pin_af_obj_t pin_G12_af[] = {
  //( 1, LPTIM   ,  1, ETR       , LPTIM1  ), // LPTIM1_ETR
  //( 5, OCTOSPIM,  0, P2_NCS    , OCTOSPIM), // OCTOSPIM_P2_NCS
#if defined(MICROPY_HW_SPI3_SCK)
  AF( 6, SPI     ,  3, NSS       , SPI3    ), // SPI3_NSS
#endif
  //( 7, USART   ,  1, RTS_DE    , USART1  ), // USART1_RTS_DE
  //(12, FMC     ,  0, NE4       , FMC     ), // FMC_NE4
  //(13, SAI     ,  2, SD_A      , SAI2    ), // SAI2_SD_A
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_G12_obj = PIN(G, 12, pin_G12_af, 0, 0);

const pin_af_obj_t pin_G13_af[] = {
#if defined(MICROPY_HW_I2C1_SCL)
  AF( 4, I2C     ,  1, SDA       , I2C1    ), // I2C1_SDA
#endif
#if defined(MICROPY_HW_UART1_TX)
  AF( 7, USART   ,  1, CK        , USART1  ), // USART1_CK
#endif
  //(11, LCD     ,  0, R0        , LCD     ), // LCD_R0
  //(12, FMC     ,  0, A24       , FMC     ), // FMC_A24
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_G13_obj = PIN(G, 13, pin_G13_af, 0, 0);

const pin_af_obj_t pin_G14_af[] = {
#if defined(MICROPY_HW_I2C1_SCL)
  AF( 4, I2C     ,  1, SCL       , I2C1    ), // I2C1_SCL
#endif
  //(11, LCD     ,  0, R1        , LCD     ), // LCD_R1
  //(12, FMC     ,  0, A25       , FMC     ), // FMC_A25
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_G14_obj = PIN(G, 14, pin_G14_af, 0, 0);

// const pin_af_obj_t pin_G15_af[] = {
  //( 1, LPTIM   ,  1, OUT       , LPTIM1  ), // LPTIM1_OUT
  //( 4, I2C     ,  1, SMBA      , I2C1    ), // I2C1_SMBA
  //( 5, OCTOSPIM,  0, P2_DQS    , OCTOSPIM), // OCTOSPIM_P2_DQS
  //(10, DCMI    ,  0, D13       , DCMI    ), // DCMI_D13
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_G15_obj = PIN(G, 15, NULL, 0, 0);

// const pin_af_obj_t pin_H0_af[] = {
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_H0_obj = PIN(H, 0, NULL, 0, 0);

// const pin_af_obj_t pin_H1_af[] = {
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_H1_obj = PIN(H, 1, NULL, 0, 0);

// const pin_af_obj_t pin_H2_af[] = {
  //( 3, OCTOSPIM,  0, P1_IO4    , OCTOSPIM), // OCTOSPIM_P1_IO4
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_H2_obj = PIN(H, 2, NULL, 0, 0);

// const pin_af_obj_t pin_H3_af[] = {
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_H3_obj = PIN(H, 3, NULL, 0, 0);

const pin_af_obj_t pin_H4_af[] = {
#if defined(MICROPY_HW_I2C2_SCL)
  AF( 4, I2C     ,  2, SCL       , I2C2    ), // I2C2_SCL
#endif
  //( 5, OCTOSPIM,  0, P2_DQS    , OCTOSPIM), // OCTOSPIM_P2_DQS
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_H4_obj = PIN(H, 4, pin_H4_af, 0, 0);

const pin_af_obj_t pin_H5_af[] = {
#if defined(MICROPY_HW_I2C2_SCL)
  AF( 4, I2C     ,  2, SDA       , I2C2    ), // I2C2_SDA
#endif
  //(10, DCMI    ,  0, PIXCLK    , DCMI    ), // DCMI_PIXCLK
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_H5_obj = PIN(H, 5, pin_H5_af, 0, 0);

// const pin_af_obj_t pin_H6_af[] = {
  //( 4, I2C     ,  2, SMBA      , I2C2    ), // I2C2_SMBA
  //( 5, OCTOSPIM,  0, P2_CLK    , OCTOSPIM), // OCTOSPIM_P2_CLK
  //(10, DCMI    ,  0, D8        , DCMI    ), // DCMI_D8
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_H6_obj = PIN(H, 6, NULL, 0, 0);

const pin_af_obj_t pin_H7_af[] = {
#if defined(MICROPY_HW_I2C3_SCL)
  AF( 4, I2C     ,  3, SCL       , I2C3    ), // I2C3_SCL
#endif
  //(10, DCMI    ,  0, D9        , DCMI    ), // DCMI_D9
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_H7_obj = PIN(H, 7, pin_H7_af, 0, 0);

const pin_af_obj_t pin_H8_af[] = {
#if defined(MICROPY_HW_I2C3_SCL)
  AF( 4, I2C     ,  3, SDA       , I2C3    ), // I2C3_SDA
#endif
  //( 5, OCTOSPIM,  0, P2_IO3    , OCTOSPIM), // OCTOSPIM_P2_IO3
  //(10, DCMI    ,  0, HSYNC     , DCMI    ), // DCMI_HSYNC
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_H8_obj = PIN(H, 8, pin_H8_af, 0, 0);

// const pin_af_obj_t pin_H9_af[] = {
  //( 4, I2C     ,  3, SMBA      , I2C3    ), // I2C3_SMBA
  //( 5, OCTOSPIM,  0, P2_IO4    , OCTOSPIM), // OCTOSPIM_P2_IO4
  //(10, DCMI    ,  0, D0        , DCMI    ), // DCMI_D0
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_H9_obj = PIN(H, 9, NULL, 0, 0);

const pin_af_obj_t pin_H10_af[] = {
  AF( 2, TIM     ,  5, CH1       , TIM5    ), // TIM5_CH1
  //( 5, OCTOSPIM,  0, P2_IO5    , OCTOSPIM), // OCTOSPIM_P2_IO5
  //(10, DCMI    ,  0, D1        , DCMI    ), // DCMI_D1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_H10_obj = PIN(H, 10, pin_H10_af, 0, 0);

const pin_af_obj_t pin_H11_af[] = {
  AF( 2, TIM     ,  5, CH2       , TIM5    ), // TIM5_CH2
  //( 5, OCTOSPIM,  0, P2_IO6    , OCTOSPIM), // OCTOSPIM_P2_IO6
  //(10, DCMI    ,  0, D2        , DCMI    ), // DCMI_D2
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_H11_obj = PIN(H, 11, pin_H11_af, 0, 0);

const pin_af_obj_t pin_H12_af[] = {
  AF( 2, TIM     ,  5, CH3       , TIM5    ), // TIM5_CH3
  //( 5, OCTOSPIM,  0, P2_IO7    , OCTOSPIM), // OCTOSPIM_P2_IO7
  //(10, DCMI    ,  0, D3        , DCMI    ), // DCMI_D3
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_H12_obj = PIN(H, 12, pin_H12_af, 0, 0);

const pin_af_obj_t pin_H13_af[] = {
  AF( 3, TIM     ,  8, CH1N      , TIM8    ), // TIM8_CH1N
#if defined(MICROPY_HW_CAN1_TX)
  AF( 9, CAN     ,  1, TX        , CAN1    ), // CAN1_TX
#endif
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_H13_obj = PIN(H, 13, pin_H13_af, 0, 0);

const pin_af_obj_t pin_H14_af[] = {
  AF( 3, TIM     ,  8, CH2N      , TIM8    ), // TIM8_CH2N
  //(10, DCMI    ,  0, D4        , DCMI    ), // DCMI_D4
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_H14_obj = PIN(H, 14, pin_H14_af, 0, 0);

const pin_af_obj_t pin_H15_af[] = {
  AF( 3, TIM     ,  8, CH3N      , TIM8    ), // TIM8_CH3N
  //( 5, OCTOSPIM,  0, P2_IO6    , OCTOSPIM), // OCTOSPIM_P2_IO6
  //(10, DCMI    ,  0, D11       , DCMI    ), // DCMI_D11
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_H15_obj = PIN(H, 15, pin_H15_af, 0, 0);

const pin_af_obj_t pin_I0_af[] = {
  AF( 2, TIM     ,  5, CH4       , TIM5    ), // TIM5_CH4
  //( 3, OCTOSPIM,  0, P1_IO5    , OCTOSPIM), // OCTOSPIM_P1_IO5
#if defined(MICROPY_HW_SPI2_SCK)
  AF( 5, SPI     ,  2, NSS       , SPI2    ), // SPI2_NSS
#endif
  //(10, DCMI    ,  0, D13       , DCMI    ), // DCMI_D13
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_I0_obj = PIN(I, 0, pin_I0_af, 0, 0);

const pin_af_obj_t pin_I1_af[] = {
#if defined(MICROPY_HW_SPI2_SCK)
  AF( 5, SPI     ,  2, SCK       , SPI2    ), // SPI2_SCK
#endif
  //(10, DCMI    ,  0, D8        , DCMI    ), // DCMI_D8
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_I1_obj = PIN(I, 1, pin_I1_af, 0, 0);

const pin_af_obj_t pin_I2_af[] = {
  AF( 3, TIM     ,  8, CH4       , TIM8    ), // TIM8_CH4
#if defined(MICROPY_HW_SPI2_SCK)
  AF( 5, SPI     ,  2, MISO      , SPI2    ), // SPI2_MISO
#endif
  //(10, DCMI    ,  0, D9        , DCMI    ), // DCMI_D9
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_I2_obj = PIN(I, 2, pin_I2_af, 0, 0);

const pin_af_obj_t pin_I3_af[] = {
  AF( 3, TIM     ,  8, ETR       , TIM8    ), // TIM8_ETR
#if defined(MICROPY_HW_SPI2_SCK)
  AF( 5, SPI     ,  2, MOSI      , SPI2    ), // SPI2_MOSI
#endif
  //(10, DCMI    ,  0, D10       , DCMI    ), // DCMI_D10
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_I3_obj = PIN(I, 3, pin_I3_af, 0, 0);

const pin_af_obj_t pin_I4_af[] = {
  AF( 3, TIM     ,  8, BKIN      , TIM8    ), // TIM8_BKIN
  //(10, DCMI    ,  0, D5        , DCMI    ), // DCMI_D5
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_I4_obj = PIN(I, 4, pin_I4_af, 0, 0);

const pin_af_obj_t pin_I5_af[] = {
  AF( 3, TIM     ,  8, CH1       , TIM8    ), // TIM8_CH1
  //( 5, OCTOSPIM,  0, P2_NCS    , OCTOSPIM), // OCTOSPIM_P2_NCS
  //(10, DCMI    ,  0, VSYNC     , DCMI    ), // DCMI_VSYNC
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_I5_obj = PIN(I, 5, pin_I5_af, 0, 0);

const pin_af_obj_t pin_I6_af[] = {
  AF( 3, TIM     ,  8, CH2       , TIM8    ), // TIM8_CH2
  //( 5, OCTOSPIM,  0, P2_CLK    , OCTOSPIM), // OCTOSPIM_P2_CLK
  //(10, DCMI    ,  0, D6        , DCMI    ), // DCMI_D6
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_I6_obj = PIN(I, 6, pin_I6_af, 0, 0);

const pin_af_obj_t pin_I7_af[] = {
  AF( 3, TIM     ,  8, CH3       , TIM8    ), // TIM8_CH3
  //(10, DCMI    ,  0, D7        , DCMI    ), // DCMI_D7
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_I7_obj = PIN(I, 7, pin_I7_af, 0, 0);

// const pin_af_obj_t pin_I8_af[] = {
  //( 5, OCTOSPIM,  0, P2_NCS    , OCTOSPIM), // OCTOSPIM_P2_NCS
  //(10, DCMI    ,  0, D12       , DCMI    ), // DCMI_D12
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_I8_obj = PIN(I, 8, NULL, 0, 0);

const pin_af_obj_t pin_I9_af[] = {
  //( 5, OCTOSPIM,  0, P2_IO2    , OCTOSPIM), // OCTOSPIM_P2_IO2
#if defined(MICROPY_HW_CAN1_TX)
  AF( 9, CAN     ,  1, RX        , CAN1    ), // CAN1_RX
#endif
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
};

const pin_obj_t pin_I9_obj = PIN(I, 9, pin_I9_af, 0, 0);

// const pin_af_obj_t pin_I10_af[] = {
  //( 5, OCTOSPIM,  0, P2_IO1    , OCTOSPIM), // OCTOSPIM_P2_IO1
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_I10_obj = PIN(I, 10, NULL, 0, 0);

// const pin_af_obj_t pin_I11_af[] = {
  //( 5, OCTOSPIM,  0, P2_IO0    , OCTOSPIM), // OCTOSPIM_P2_IO0
  //(15, EVENTOUT,  0,           , EVENTOUT), // EVENTOUT
// };

const pin_obj_t pin_I11_obj = PIN(I, 11, NULL, 0, 0);

STATIC const mp_rom_map_elem_t pin_cpu_pins_locals_dict_table[] = {
  { MP_ROM_QSTR(MP_QSTR_A0), MP_ROM_PTR(&pin_A0_obj) },
  { MP_ROM_QSTR(MP_QSTR_A1), MP_ROM_PTR(&pin_A1_obj) },
  { MP_ROM_QSTR(MP_QSTR_A2), MP_ROM_PTR(&pin_A2_obj) },
  { MP_ROM_QSTR(MP_QSTR_A3), MP_ROM_PTR(&pin_A3_obj) },
  { MP_ROM_QSTR(MP_QSTR_A4), MP_ROM_PTR(&pin_A4_obj) },
  { MP_ROM_QSTR(MP_QSTR_A5), MP_ROM_PTR(&pin_A5_obj) },
  { MP_ROM_QSTR(MP_QSTR_A6), MP_ROM_PTR(&pin_A6_obj) },
  { MP_ROM_QSTR(MP_QSTR_A7), MP_ROM_PTR(&pin_A7_obj) },
  { MP_ROM_QSTR(MP_QSTR_A8), MP_ROM_PTR(&pin_A8_obj) },
  { MP_ROM_QSTR(MP_QSTR_A9), MP_ROM_PTR(&pin_A9_obj) },
  { MP_ROM_QSTR(MP_QSTR_A10), MP_ROM_PTR(&pin_A10_obj) },
  { MP_ROM_QSTR(MP_QSTR_A11), MP_ROM_PTR(&pin_A11_obj) },
  { MP_ROM_QSTR(MP_QSTR_A12), MP_ROM_PTR(&pin_A12_obj) },
  { MP_ROM_QSTR(MP_QSTR_A13), MP_ROM_PTR(&pin_A13_obj) },
  { MP_ROM_QSTR(MP_QSTR_A14), MP_ROM_PTR(&pin_A14_obj) },
  { MP_ROM_QSTR(MP_QSTR_A15), MP_ROM_PTR(&pin_A15_obj) },
  { MP_ROM_QSTR(MP_QSTR_B0), MP_ROM_PTR(&pin_B0_obj) },
  { MP_ROM_QSTR(MP_QSTR_B1), MP_ROM_PTR(&pin_B1_obj) },
  { MP_ROM_QSTR(MP_QSTR_B2), MP_ROM_PTR(&pin_B2_obj) },
  { MP_ROM_QSTR(MP_QSTR_B3), MP_ROM_PTR(&pin_B3_obj) },
  { MP_ROM_QSTR(MP_QSTR_B4), MP_ROM_PTR(&pin_B4_obj) },
  { MP_ROM_QSTR(MP_QSTR_B5), MP_ROM_PTR(&pin_B5_obj) },
  { MP_ROM_QSTR(MP_QSTR_B6), MP_ROM_PTR(&pin_B6_obj) },
  { MP_ROM_QSTR(MP_QSTR_B7), MP_ROM_PTR(&pin_B7_obj) },
  { MP_ROM_QSTR(MP_QSTR_B8), MP_ROM_PTR(&pin_B8_obj) },
  { MP_ROM_QSTR(MP_QSTR_B9), MP_ROM_PTR(&pin_B9_obj) },
  { MP_ROM_QSTR(MP_QSTR_B10), MP_ROM_PTR(&pin_B10_obj) },
  { MP_ROM_QSTR(MP_QSTR_B11), MP_ROM_PTR(&pin_B11_obj) },
  { MP_ROM_QSTR(MP_QSTR_B12), MP_ROM_PTR(&pin_B12_obj) },
  { MP_ROM_QSTR(MP_QSTR_B13), MP_ROM_PTR(&pin_B13_obj) },
  { MP_ROM_QSTR(MP_QSTR_B14), MP_ROM_PTR(&pin_B14_obj) },
  { MP_ROM_QSTR(MP_QSTR_B15), MP_ROM_PTR(&pin_B15_obj) },
  { MP_ROM_QSTR(MP_QSTR_C0), MP_ROM_PTR(&pin_C0_obj) },
  { MP_ROM_QSTR(MP_QSTR_C1), MP_ROM_PTR(&pin_C1_obj) },
  { MP_ROM_QSTR(MP_QSTR_C2), MP_ROM_PTR(&pin_C2_obj) },
  { MP_ROM_QSTR(MP_QSTR_C3), MP_ROM_PTR(&pin_C3_obj) },
  { MP_ROM_QSTR(MP_QSTR_C4), MP_ROM_PTR(&pin_C4_obj) },
  { MP_ROM_QSTR(MP_QSTR_C5), MP_ROM_PTR(&pin_C5_obj) },
  { MP_ROM_QSTR(MP_QSTR_C6), MP_ROM_PTR(&pin_C6_obj) },
  { MP_ROM_QSTR(MP_QSTR_C7), MP_ROM_PTR(&pin_C7_obj) },
  { MP_ROM_QSTR(MP_QSTR_C8), MP_ROM_PTR(&pin_C8_obj) },
  { MP_ROM_QSTR(MP_QSTR_C9), MP_ROM_PTR(&pin_C9_obj) },
  { MP_ROM_QSTR(MP_QSTR_C10), MP_ROM_PTR(&pin_C10_obj) },
  { MP_ROM_QSTR(MP_QSTR_C11), MP_ROM_PTR(&pin_C11_obj) },
  { MP_ROM_QSTR(MP_QSTR_C12), MP_ROM_PTR(&pin_C12_obj) },
  { MP_ROM_QSTR(MP_QSTR_C13), MP_ROM_PTR(&pin_C13_obj) },
  { MP_ROM_QSTR(MP_QSTR_C14), MP_ROM_PTR(&pin_C14_obj) },
  { MP_ROM_QSTR(MP_QSTR_C15), MP_ROM_PTR(&pin_C15_obj) },
  { MP_ROM_QSTR(MP_QSTR_D0), MP_ROM_PTR(&pin_D0_obj) },
  { MP_ROM_QSTR(MP_QSTR_D1), MP_ROM_PTR(&pin_D1_obj) },
  { MP_ROM_QSTR(MP_QSTR_D2), MP_ROM_PTR(&pin_D2_obj) },
  { MP_ROM_QSTR(MP_QSTR_D3), MP_ROM_PTR(&pin_D3_obj) },
  { MP_ROM_QSTR(MP_QSTR_D4), MP_ROM_PTR(&pin_D4_obj) },
  { MP_ROM_QSTR(MP_QSTR_D5), MP_ROM_PTR(&pin_D5_obj) },
  { MP_ROM_QSTR(MP_QSTR_D6), MP_ROM_PTR(&pin_D6_obj) },
  { MP_ROM_QSTR(MP_QSTR_D7), MP_ROM_PTR(&pin_D7_obj) },
  { MP_ROM_QSTR(MP_QSTR_D8), MP_ROM_PTR(&pin_D8_obj) },
  { MP_ROM_QSTR(MP_QSTR_D9), MP_ROM_PTR(&pin_D9_obj) },
  { MP_ROM_QSTR(MP_QSTR_D10), MP_ROM_PTR(&pin_D10_obj) },
  { MP_ROM_QSTR(MP_QSTR_D11), MP_ROM_PTR(&pin_D11_obj) },
  { MP_ROM_QSTR(MP_QSTR_D12), MP_ROM_PTR(&pin_D12_obj) },
  { MP_ROM_QSTR(MP_QSTR_D13), MP_ROM_PTR(&pin_D13_obj) },
  { MP_ROM_QSTR(MP_QSTR_D14), MP_ROM_PTR(&pin_D14_obj) },
  { MP_ROM_QSTR(MP_QSTR_D15), MP_ROM_PTR(&pin_D15_obj) },
  { MP_ROM_QSTR(MP_QSTR_E0), MP_ROM_PTR(&pin_E0_obj) },
  { MP_ROM_QSTR(MP_QSTR_E1), MP_ROM_PTR(&pin_E1_obj) },
  { MP_ROM_QSTR(MP_QSTR_E2), MP_ROM_PTR(&pin_E2_obj) },
  { MP_ROM_QSTR(MP_QSTR_E3), MP_ROM_PTR(&pin_E3_obj) },
  { MP_ROM_QSTR(MP_QSTR_E4), MP_ROM_PTR(&pin_E4_obj) },
  { MP_ROM_QSTR(MP_QSTR_E5), MP_ROM_PTR(&pin_E5_obj) },
  { MP_ROM_QSTR(MP_QSTR_E6), MP_ROM_PTR(&pin_E6_obj) },
  { MP_ROM_QSTR(MP_QSTR_E7), MP_ROM_PTR(&pin_E7_obj) },
  { MP_ROM_QSTR(MP_QSTR_E8), MP_ROM_PTR(&pin_E8_obj) },
  { MP_ROM_QSTR(MP_QSTR_E9), MP_ROM_PTR(&pin_E9_obj) },
  { MP_ROM_QSTR(MP_QSTR_E10), MP_ROM_PTR(&pin_E10_obj) },
  { MP_ROM_QSTR(MP_QSTR_E11), MP_ROM_PTR(&pin_E11_obj) },
  { MP_ROM_QSTR(MP_QSTR_E12), MP_ROM_PTR(&pin_E12_obj) },
  { MP_ROM_QSTR(MP_QSTR_E13), MP_ROM_PTR(&pin_E13_obj) },
  { MP_ROM_QSTR(MP_QSTR_E14), MP_ROM_PTR(&pin_E14_obj) },
  { MP_ROM_QSTR(MP_QSTR_E15), MP_ROM_PTR(&pin_E15_obj) },
  { MP_ROM_QSTR(MP_QSTR_F0), MP_ROM_PTR(&pin_F0_obj) },
  { MP_ROM_QSTR(MP_QSTR_F1), MP_ROM_PTR(&pin_F1_obj) },
  { MP_ROM_QSTR(MP_QSTR_F2), MP_ROM_PTR(&pin_F2_obj) },
  { MP_ROM_QSTR(MP_QSTR_F3), MP_ROM_PTR(&pin_F3_obj) },
  { MP_ROM_QSTR(MP_QSTR_F4), MP_ROM_PTR(&pin_F4_obj) },
  { MP_ROM_QSTR(MP_QSTR_F5), MP_ROM_PTR(&pin_F5_obj) },
  { MP_ROM_QSTR(MP_QSTR_F6), MP_ROM_PTR(&pin_F6_obj) },
  { MP_ROM_QSTR(MP_QSTR_F7), MP_ROM_PTR(&pin_F7_obj) },
  { MP_ROM_QSTR(MP_QSTR_F8), MP_ROM_PTR(&pin_F8_obj) },
  { MP_ROM_QSTR(MP_QSTR_F9), MP_ROM_PTR(&pin_F9_obj) },
  { MP_ROM_QSTR(MP_QSTR_F10), MP_ROM_PTR(&pin_F10_obj) },
  { MP_ROM_QSTR(MP_QSTR_F11), MP_ROM_PTR(&pin_F11_obj) },
  { MP_ROM_QSTR(MP_QSTR_F12), MP_ROM_PTR(&pin_F12_obj) },
  { MP_ROM_QSTR(MP_QSTR_F13), MP_ROM_PTR(&pin_F13_obj) },
  { MP_ROM_QSTR(MP_QSTR_F14), MP_ROM_PTR(&pin_F14_obj) },
  { MP_ROM_QSTR(MP_QSTR_F15), MP_ROM_PTR(&pin_F15_obj) },
  { MP_ROM_QSTR(MP_QSTR_G0), MP_ROM_PTR(&pin_G0_obj) },
  { MP_ROM_QSTR(MP_QSTR_G1), MP_ROM_PTR(&pin_G1_obj) },
  { MP_ROM_QSTR(MP_QSTR_G2), MP_ROM_PTR(&pin_G2_obj) },
  { MP_ROM_QSTR(MP_QSTR_G3), MP_ROM_PTR(&pin_G3_obj) },
  { MP_ROM_QSTR(MP_QSTR_G4), MP_ROM_PTR(&pin_G4_obj) },
  { MP_ROM_QSTR(MP_QSTR_G5), MP_ROM_PTR(&pin_G5_obj) },
  { MP_ROM_QSTR(MP_QSTR_G6), MP_ROM_PTR(&pin_G6_obj) },
  { MP_ROM_QSTR(MP_QSTR_G7), MP_ROM_PTR(&pin_G7_obj) },
  { MP_ROM_QSTR(MP_QSTR_G8), MP_ROM_PTR(&pin_G8_obj) },
  { MP_ROM_QSTR(MP_QSTR_G9), MP_ROM_PTR(&pin_G9_obj) },
  { MP_ROM_QSTR(MP_QSTR_G10), MP_ROM_PTR(&pin_G10_obj) },
  { MP_ROM_QSTR(MP_QSTR_G11), MP_ROM_PTR(&pin_G11_obj) },
  { MP_ROM_QSTR(MP_QSTR_G12), MP_ROM_PTR(&pin_G12_obj) },
  { MP_ROM_QSTR(MP_QSTR_G13), MP_ROM_PTR(&pin_G13_obj) },
  { MP_ROM_QSTR(MP_QSTR_G14), MP_ROM_PTR(&pin_G14_obj) },
  { MP_ROM_QSTR(MP_QSTR_G15), MP_ROM_PTR(&pin_G15_obj) },
  { MP_ROM_QSTR(MP_QSTR_H0), MP_ROM_PTR(&pin_H0_obj) },
  { MP_ROM_QSTR(MP_QSTR_H1), MP_ROM_PTR(&pin_H1_obj) },
  { MP_ROM_QSTR(MP_QSTR_H2), MP_ROM_PTR(&pin_H2_obj) },
  { MP_ROM_QSTR(MP_QSTR_H3), MP_ROM_PTR(&pin_H3_obj) },
  { MP_ROM_QSTR(MP_QSTR_H4), MP_ROM_PTR(&pin_H4_obj) },
  { MP_ROM_QSTR(MP_QSTR_H5), MP_ROM_PTR(&pin_H5_obj) },
  { MP_ROM_QSTR(MP_QSTR_H6), MP_ROM_PTR(&pin_H6_obj) },
  { MP_ROM_QSTR(MP_QSTR_H7), MP_ROM_PTR(&pin_H7_obj) },
  { MP_ROM_QSTR(MP_QSTR_H8), MP_ROM_PTR(&pin_H8_obj) },
  { MP_ROM_QSTR(MP_QSTR_H9), MP_ROM_PTR(&pin_H9_obj) },
  { MP_ROM_QSTR(MP_QSTR_H10), MP_ROM_PTR(&pin_H10_obj) },
  { MP_ROM_QSTR(MP_QSTR_H11), MP_ROM_PTR(&pin_H11_obj) },
  { MP_ROM_QSTR(MP_QSTR_H12), MP_ROM_PTR(&pin_H12_obj) },
  { MP_ROM_QSTR(MP_QSTR_H13), MP_ROM_PTR(&pin_H13_obj) },
  { MP_ROM_QSTR(MP_QSTR_H14), MP_ROM_PTR(&pin_H14_obj) },
  { MP_ROM_QSTR(MP_QSTR_H15), MP_ROM_PTR(&pin_H15_obj) },
  { MP_ROM_QSTR(MP_QSTR_I0), MP_ROM_PTR(&pin_I0_obj) },
  { MP_ROM_QSTR(MP_QSTR_I1), MP_ROM_PTR(&pin_I1_obj) },
  { MP_ROM_QSTR(MP_QSTR_I2), MP_ROM_PTR(&pin_I2_obj) },
  { MP_ROM_QSTR(MP_QSTR_I3), MP_ROM_PTR(&pin_I3_obj) },
  { MP_ROM_QSTR(MP_QSTR_I4), MP_ROM_PTR(&pin_I4_obj) },
  { MP_ROM_QSTR(MP_QSTR_I5), MP_ROM_PTR(&pin_I5_obj) },
  { MP_ROM_QSTR(MP_QSTR_I6), MP_ROM_PTR(&pin_I6_obj) },
  { MP_ROM_QSTR(MP_QSTR_I7), MP_ROM_PTR(&pin_I7_obj) },
  { MP_ROM_QSTR(MP_QSTR_I8), MP_ROM_PTR(&pin_I8_obj) },
  { MP_ROM_QSTR(MP_QSTR_I9), MP_ROM_PTR(&pin_I9_obj) },
  { MP_ROM_QSTR(MP_QSTR_I10), MP_ROM_PTR(&pin_I10_obj) },
  { MP_ROM_QSTR(MP_QSTR_I11), MP_ROM_PTR(&pin_I11_obj) },
};
MP_DEFINE_CONST_DICT(pin_cpu_pins_locals_dict, pin_cpu_pins_locals_dict_table);

STATIC const mp_rom_map_elem_t pin_board_pins_locals_dict_table[] = {
  { MP_ROM_QSTR(MP_QSTR_PA0), MP_ROM_PTR(&pin_A0_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA1), MP_ROM_PTR(&pin_A1_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA2), MP_ROM_PTR(&pin_A2_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA3), MP_ROM_PTR(&pin_A3_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA4), MP_ROM_PTR(&pin_A4_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA5), MP_ROM_PTR(&pin_A5_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA6), MP_ROM_PTR(&pin_A6_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA7), MP_ROM_PTR(&pin_A7_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA8), MP_ROM_PTR(&pin_A8_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA9), MP_ROM_PTR(&pin_A9_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA10), MP_ROM_PTR(&pin_A10_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA11), MP_ROM_PTR(&pin_A11_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA12), MP_ROM_PTR(&pin_A12_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA13), MP_ROM_PTR(&pin_A13_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA14), MP_ROM_PTR(&pin_A14_obj) },
  { MP_ROM_QSTR(MP_QSTR_PA15), MP_ROM_PTR(&pin_A15_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB0), MP_ROM_PTR(&pin_B0_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB1), MP_ROM_PTR(&pin_B1_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB2), MP_ROM_PTR(&pin_B2_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB3), MP_ROM_PTR(&pin_B3_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB4), MP_ROM_PTR(&pin_B4_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB5), MP_ROM_PTR(&pin_B5_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB6), MP_ROM_PTR(&pin_B6_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB7), MP_ROM_PTR(&pin_B7_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB8), MP_ROM_PTR(&pin_B8_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB9), MP_ROM_PTR(&pin_B9_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB10), MP_ROM_PTR(&pin_B10_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB11), MP_ROM_PTR(&pin_B11_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB12), MP_ROM_PTR(&pin_B12_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB13), MP_ROM_PTR(&pin_B13_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB14), MP_ROM_PTR(&pin_B14_obj) },
  { MP_ROM_QSTR(MP_QSTR_PB15), MP_ROM_PTR(&pin_B15_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC0), MP_ROM_PTR(&pin_C0_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC1), MP_ROM_PTR(&pin_C1_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC2), MP_ROM_PTR(&pin_C2_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC3), MP_ROM_PTR(&pin_C3_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC4), MP_ROM_PTR(&pin_C4_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC5), MP_ROM_PTR(&pin_C5_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC6), MP_ROM_PTR(&pin_C6_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC7), MP_ROM_PTR(&pin_C7_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC8), MP_ROM_PTR(&pin_C8_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC9), MP_ROM_PTR(&pin_C9_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC10), MP_ROM_PTR(&pin_C10_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC11), MP_ROM_PTR(&pin_C11_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC12), MP_ROM_PTR(&pin_C12_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC13), MP_ROM_PTR(&pin_C13_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC14), MP_ROM_PTR(&pin_C14_obj) },
  { MP_ROM_QSTR(MP_QSTR_PC15), MP_ROM_PTR(&pin_C15_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD0), MP_ROM_PTR(&pin_D0_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD1), MP_ROM_PTR(&pin_D1_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD2), MP_ROM_PTR(&pin_D2_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD3), MP_ROM_PTR(&pin_D3_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD4), MP_ROM_PTR(&pin_D4_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD5), MP_ROM_PTR(&pin_D5_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD6), MP_ROM_PTR(&pin_D6_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD7), MP_ROM_PTR(&pin_D7_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD8), MP_ROM_PTR(&pin_D8_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD9), MP_ROM_PTR(&pin_D9_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD10), MP_ROM_PTR(&pin_D10_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD11), MP_ROM_PTR(&pin_D11_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD12), MP_ROM_PTR(&pin_D12_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD13), MP_ROM_PTR(&pin_D13_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD14), MP_ROM_PTR(&pin_D14_obj) },
  { MP_ROM_QSTR(MP_QSTR_PD15), MP_ROM_PTR(&pin_D15_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE0), MP_ROM_PTR(&pin_E0_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE1), MP_ROM_PTR(&pin_E1_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE2), MP_ROM_PTR(&pin_E2_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE3), MP_ROM_PTR(&pin_E3_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE4), MP_ROM_PTR(&pin_E4_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE5), MP_ROM_PTR(&pin_E5_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE6), MP_ROM_PTR(&pin_E6_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE7), MP_ROM_PTR(&pin_E7_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE8), MP_ROM_PTR(&pin_E8_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE9), MP_ROM_PTR(&pin_E9_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE10), MP_ROM_PTR(&pin_E10_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE11), MP_ROM_PTR(&pin_E11_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE12), MP_ROM_PTR(&pin_E12_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE13), MP_ROM_PTR(&pin_E13_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE14), MP_ROM_PTR(&pin_E14_obj) },
  { MP_ROM_QSTR(MP_QSTR_PE15), MP_ROM_PTR(&pin_E15_obj) },
  { MP_ROM_QSTR(MP_QSTR_PF0), MP_ROM_PTR(&pin_F0_obj) },
  { MP_ROM_QSTR(MP_QSTR_PF1), MP_ROM_PTR(&pin_F1_obj) },
  { MP_ROM_QSTR(MP_QSTR_PF2), MP_ROM_PTR(&pin_F2_obj) },
  { MP_ROM_QSTR(MP_QSTR_PF3), MP_ROM_PTR(&pin_F3_obj) },
  { MP_ROM_QSTR(MP_QSTR_PF4), MP_ROM_PTR(&pin_F4_obj) },
  { MP_ROM_QSTR(MP_QSTR_PF5), MP_ROM_PTR(&pin_F5_obj) },
  { MP_ROM_QSTR(MP_QSTR_PF6), MP_ROM_PTR(&pin_F6_obj) },
  { MP_ROM_QSTR(MP_QSTR_PF7), MP_ROM_PTR(&pin_F7_obj) },
  { MP_ROM_QSTR(MP_QSTR_PF8), MP_ROM_PTR(&pin_F8_obj) },
  { MP_ROM_QSTR(MP_QSTR_PF9), MP_ROM_PTR(&pin_F9_obj) },
  { MP_ROM_QSTR(MP_QSTR_PF10), MP_ROM_PTR(&pin_F10_obj) },
  { MP_ROM_QSTR(MP_QSTR_PF11), MP_ROM_PTR(&pin_F11_obj) },
  { MP_ROM_QSTR(MP_QSTR_PF12), MP_ROM_PTR(&pin_F12_obj) },
  { MP_ROM_QSTR(MP_QSTR_PF13), MP_ROM_PTR(&pin_F13_obj) },
  { MP_ROM_QSTR(MP_QSTR_PF14), MP_ROM_PTR(&pin_F14_obj) },
  { MP_ROM_QSTR(MP_QSTR_PF15), MP_ROM_PTR(&pin_F15_obj) },
  { MP_ROM_QSTR(MP_QSTR_PG0), MP_ROM_PTR(&pin_G0_obj) },
  { MP_ROM_QSTR(MP_QSTR_PG1), MP_ROM_PTR(&pin_G1_obj) },
  { MP_ROM_QSTR(MP_QSTR_PG2), MP_ROM_PTR(&pin_G2_obj) },
  { MP_ROM_QSTR(MP_QSTR_PG3), MP_ROM_PTR(&pin_G3_obj) },
  { MP_ROM_QSTR(MP_QSTR_PG4), MP_ROM_PTR(&pin_G4_obj) },
  { MP_ROM_QSTR(MP_QSTR_PG5), MP_ROM_PTR(&pin_G5_obj) },
  { MP_ROM_QSTR(MP_QSTR_PG6), MP_ROM_PTR(&pin_G6_obj) },
  { MP_ROM_QSTR(MP_QSTR_PG7), MP_ROM_PTR(&pin_G7_obj) },
  { MP_ROM_QSTR(MP_QSTR_PG8), MP_ROM_PTR(&pin_G8_obj) },
  { MP_ROM_QSTR(MP_QSTR_PG9), MP_ROM_PTR(&pin_G9_obj) },
  { MP_ROM_QSTR(MP_QSTR_PG10), MP_ROM_PTR(&pin_G10_obj) },
  { MP_ROM_QSTR(MP_QSTR_PG11), MP_ROM_PTR(&pin_G11_obj) },
  { MP_ROM_QSTR(MP_QSTR_PG12), MP_ROM_PTR(&pin_G12_obj) },
  { MP_ROM_QSTR(MP_QSTR_PG13), MP_ROM_PTR(&pin_G13_obj) },
  { MP_ROM_QSTR(MP_QSTR_PG14), MP_ROM_PTR(&pin_G14_obj) },
  { MP_ROM_QSTR(MP_QSTR_PG15), MP_ROM_PTR(&pin_G15_obj) },
  { MP_ROM_QSTR(MP_QSTR_PH0), MP_ROM_PTR(&pin_H0_obj) },
  { MP_ROM_QSTR(MP_QSTR_PH1), MP_ROM_PTR(&pin_H1_obj) },
  { MP_ROM_QSTR(MP_QSTR_PH2), MP_ROM_PTR(&pin_H2_obj) },
  { MP_ROM_QSTR(MP_QSTR_PH3), MP_ROM_PTR(&pin_H3_obj) },
  { MP_ROM_QSTR(MP_QSTR_PH4), MP_ROM_PTR(&pin_H4_obj) },
  { MP_ROM_QSTR(MP_QSTR_PH5), MP_ROM_PTR(&pin_H5_obj) },
  { MP_ROM_QSTR(MP_QSTR_PH6), MP_ROM_PTR(&pin_H6_obj) },
  { MP_ROM_QSTR(MP_QSTR_PH7), MP_ROM_PTR(&pin_H7_obj) },
  { MP_ROM_QSTR(MP_QSTR_PH8), MP_ROM_PTR(&pin_H8_obj) },
  { MP_ROM_QSTR(MP_QSTR_PH9), MP_ROM_PTR(&pin_H9_obj) },
  { MP_ROM_QSTR(MP_QSTR_PH10), MP_ROM_PTR(&pin_H10_obj) },
  { MP_ROM_QSTR(MP_QSTR_PH11), MP_ROM_PTR(&pin_H11_obj) },
  { MP_ROM_QSTR(MP_QSTR_PH12), MP_ROM_PTR(&pin_H12_obj) },
  { MP_ROM_QSTR(MP_QSTR_PH13), MP_ROM_PTR(&pin_H13_obj) },
  { MP_ROM_QSTR(MP_QSTR_PH14), MP_ROM_PTR(&pin_H14_obj) },
  { MP_ROM_QSTR(MP_QSTR_PH15), MP_ROM_PTR(&pin_H15_obj) },
  { MP_ROM_QSTR(MP_QSTR_PI0), MP_ROM_PTR(&pin_I0_obj) },
  { MP_ROM_QSTR(MP_QSTR_PI1), MP_ROM_PTR(&pin_I1_obj) },
  { MP_ROM_QSTR(MP_QSTR_PI2), MP_ROM_PTR(&pin_I2_obj) },
  { MP_ROM_QSTR(MP_QSTR_PI3), MP_ROM_PTR(&pin_I3_obj) },
  { MP_ROM_QSTR(MP_QSTR_PI4), MP_ROM_PTR(&pin_I4_obj) },
  { MP_ROM_QSTR(MP_QSTR_PI5), MP_ROM_PTR(&pin_I5_obj) },
  { MP_ROM_QSTR(MP_QSTR_PI6), MP_ROM_PTR(&pin_I6_obj) },
  { MP_ROM_QSTR(MP_QSTR_PI7), MP_ROM_PTR(&pin_I7_obj) },
  { MP_ROM_QSTR(MP_QSTR_PI8), MP_ROM_PTR(&pin_I8_obj) },
  { MP_ROM_QSTR(MP_QSTR_PI9), MP_ROM_PTR(&pin_I9_obj) },
  { MP_ROM_QSTR(MP_QSTR_PI10), MP_ROM_PTR(&pin_I10_obj) },
  { MP_ROM_QSTR(MP_QSTR_PI11), MP_ROM_PTR(&pin_I11_obj) },
};
MP_DEFINE_CONST_DICT(pin_board_pins_locals_dict, pin_board_pins_locals_dict_table);

const pin_obj_t * const pin_adc1[] = {
  NULL,    // 0
  &pin_C0_obj, // 1
  &pin_C1_obj, // 2
  &pin_C2_obj, // 3
  &pin_C3_obj, // 4
  &pin_A0_obj, // 5
  &pin_A1_obj, // 6
  &pin_A2_obj, // 7
  &pin_A3_obj, // 8
  &pin_A4_obj, // 9
  &pin_A5_obj, // 10
  &pin_A6_obj, // 11
  &pin_A7_obj, // 12
  &pin_C4_obj, // 13
  &pin_C5_obj, // 14
  &pin_B0_obj, // 15
#if defined(STM32L4)
  &pin_B1_obj, // 16
#endif
};

const pin_obj_t * const pin_adc2[] = {
  NULL,    // 0
  NULL,    // 1
  NULL,    // 2
  NULL,    // 3
  NULL,    // 4
  NULL,    // 5
  NULL,    // 6
  NULL,    // 7
  NULL,    // 8
  NULL,    // 9
  NULL,    // 10
  NULL,    // 11
  NULL,    // 12
  NULL,    // 13
  NULL,    // 14
  NULL,    // 15
#if defined(STM32L4)
  NULL,    // 16
#endif
};

const pin_obj_t * const pin_adc3[] = {
  NULL,    // 0
  NULL,    // 1
  NULL,    // 2
  NULL,    // 3
  NULL,    // 4
  NULL,    // 5
  NULL,    // 6
  NULL,    // 7
  NULL,    // 8
  NULL,    // 9
  NULL,    // 10
  NULL,    // 11
  NULL,    // 12
  NULL,    // 13
  NULL,    // 14
  NULL,    // 15
#if defined(STM32L4)
  NULL,    // 16
#endif
};
